### ISSUE TITLE
Newest podio potentially depends on sio, but sio only lives here

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#104]
After merging AIDASoft/podio#130 podio can now support `sio` as I/O backend. When updating the `package.py` of podio in the central spack repository I realized that `sio` still lives here, so podio will probably not work in standalone spack. Should we consider moving the `sio` package to the central spack repository?

**Comment by vvolkl** [comment]
Yes, I think that's the  best solution! Since `sio` does not have a lot of dependencies, it should be no problem.
