### ISSUE TITLE
gaudimarlinwrapper looking for cmake file not in Gaudi 35.0

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#107]
This seems to be because the files are different with Gaudi 35.0

CMake Warning at CMakeLists.txt:50 (find_package):
  By not providing "FindGaudiProject.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "GaudiProject", but CMake did not find one.
  Could not find a package configuration file provided by "GaudiProject" with
  any of the following names:
    GaudiProjectConfig.cmake
    gaudiproject-config.cmake
  Add the installation prefix of "GaudiProject" to CMAKE_PREFIX_PATH or set
  "GaudiProject_DIR" to a directory containing one of the above files.  If
  "GaudiProject" provides a separate development package or SDK, be sure it
  has been installed.
CMake Error at CMakeLists.txt:55 (gaudi_project):
  Unknown CMake command "gaudi_project".

**Comment by vvolkl** [comment]
Hi @joequant 

yes, v35 overhauled the cmake configuration of gaudi with some big improvements, but requires updates to the usercode (see https://github.com/key4hep/k4FWCore/pull/19). We should tackle this now that v35 is released, let's discuss it at the next meeting.
