### ISSUE TITLE
RooFit not linked

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/key4hep-spack#128]
Looks like when using the latest setup RooFit is not linked at least from python (import ROOT.RooFit as rf)
If we are going to rebuild with a new ROOT version, it would be good to at least use v6.22/04 to solve the 2 RootDataFrame issues raised here:

https://root-forum.cern.ch/t/question-on-memory-comsumption-with-rdf/42205/2

**Comment by vvolkl** [comment]
That's true and is a bug in the upstream spack root recipe. I think v6.22/04 has been removed due to a bug, but we'll move to v6.22/06 when it is released.

**Comment by vvolkl** [comment]
https://github.com/spack/spack/pull/20051

**Comment by tmadlener** [comment]
Closing this, since the most recent release (2020-12-15) has root v6.22/06 with RooFit
