### ISSUE TITLE
Some of the missing (or to be updated) python tools for downstream analysis

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/key4hep-spack#158]
Here is a non-exhaustive list of nice to have python tools (to be edited/completed as we go):

- [x] pandas
- ([ ] root_pandas)
- [x] xgboost
- [x] sklearn
- [x] scipy
- [ ] zfit

**Comment by clementhelsens** [comment]
@vvolkl , I'm using this issue also to track updates in packages as well. The uproot version we have installed is 0.0.27 which dates from 18 Sept 2020.
There was a nice development requested by us, namely ability to read RVec. Version 0.1.2 should have it in.
As I'm trying to limit the number of tools that I installed locally, would it be possible to update this one?

**Comment by vvolkl** [comment]
Hi @clementhelsens,

thanks for opening this issue, that's much nicer to keep track. For the python tools, pandas, sklearn and scipy are easy to add, the others need new recipes, so that might need some time. 

For uproot, I just added the new versions: https://github.com/spack/spack/pull/21588/files

The newest one is 4.0.2, let me know if that is fine too.

**Comment by clementhelsens** [comment]
@vvolkl , indeed, for uproot, they changed uproot4 to uproot, so the version we are using locally is indeed the one you are referring too. Please ping here when some of the above are in the stack.

If we could little by little remove the dependencies to locally installed python tools I am perfectly fine with this.
Tagging @donalrinho so that he knows we will need to remove uproot from our local install.

**Comment by vvolkl** [comment]
Some zfit dependencies that are not yet in spack:

- [ ] colored
- [ ] numdifftools
- [ ] tensorflow-addons
- [ ] ordered-set

**Comment by vvolkl** [comment]
@clementhelsens I don't think root_pandas is needed. We already use a ROOT version that has similar functionality, see https://github.com/root-project/root/blob/v6-22-06/tutorials/pyroot/pyroot002_TTreeAsMatrix.py

**Comment by donalrinho** [comment]
`root_pandas` functionality can be taken from `uproot` I think, if dataframes are needed from ROOT files.

**Comment by clementhelsens** [comment]
agree @vvolkl , I trust @donalrinho on this one as I just added the packages to reproduce what was done standalone.
I could give it a try later this week to confirm, unless @donalrinho is confident about it

**Comment by vvolkl** [comment]
Closing - we added everything except zfit. If this is needed another issue should be opened.
