### ISSUE TITLE
Pandora CMakeTools - better installations

### ISSUE THREAD

**Issue by vvolkl** [key4hep/key4hep-spack#161]
Currently, PandoraPFA/cmaketools needs to be explicitly added to CMAKE_MODULE_PATH, and some patches are required for the pandora packages. Would be nice to get rid of this - the first step will probably updating the pandora versions.

**Comment by jmcarcell** [comment]
PandoraPFA isn't anymore in this repository, see `https://github.com/key4hep/key4hep-spack/pull/618`. The current recipe doesn't have patches but the `CMAKE_MODULE_PATH` is still true for some packages.
