### ISSUE TITLE
dd4hep (ddsim) failing to parse XML files

### ISSUE THREAD

**Issue by andresailer** [key4hep/key4hep-spack#170]
- OS version: centos7
 - Compiler version: eGCC 8.3
 - Package version: /cvmfs/sw.hsf.org/spackages/linux-centos7-broadwell/gcc-8.3.0/key4hep-stack-2021-03-01a-3wtd62edhsgasex7wnvdu7rijlzbizni/setup.sh

The last that worked was 
/cvmfs/sw.hsf.org/spackages/linux-centos7-broadwell/gcc-8.3.0/key4hep-stack-2020-12-10-gfd2wztpjsmf4uvxs6irf2c6dxzfo7y7/setup.sh 

- Reproducer
```
/cvmfs/sw.hsf.org/spackages/linux-centos7-broadwell/gcc-8.3.0/key4hep-stack-2021-03-01a-3wtd62edhsgasex7wnvdu7rijlzbizni/setup.sh
ddsim --compactFile $lcgeo_DIR/share/lcgeo/compact/CLIC/compact/CLIC_o3_v14/CLIC_o3_v14.xml  -G -N 10 --gun.particle=mu- --gun.distribution uniform --gun.energy "1*GeV" -O muons.slcio 
```
Gives the error message
```
Could not load a transcoding service
```

I think this is related to the XercesC XML parsing in some way.
Does instantiating DD4hep XML files work via gaudi in this release?

It gets fixed by
```
export LC_ALL=C
```

**Comment by vvolkl** [comment]
Ah, interesting, indeed Gaudi does set `LC_ALL=C` in its run script, which is why I didn't  see any error. Should we just add this to the environment?

**Comment by andresailer** [comment]
probably then the easiest solution.

**Comment by vvolkl** [comment]
I cannot reproduce that on lxplus, by the way. Do you maybe set a custom locale somewhere?

**Comment by andresailer** [comment]
Fails for me also on aiadm, I don't have anything in my .bashrc
```
$ env | grep LANG
LANG=en_GB.utf8
LANGUAGE=en
```
(nothing for LC)
Do you set a custom locale?

**Comment by vvolkl** [comment]
No, nothing in my `.bashrc`, but:
```
~$ env | grep LANG
LANG=en_US.UTF-8
~$ echo $LC

~$ 
```
Indeed I can reproduce it setting those two env vars. Seems that there is some variance even for normal CERN accounts? In any case, the setup script should be robust for all these cases.

**Comment by andresailer** [comment]
hmm, weird that I get `en_GB`... and not US.

**Comment by andresailer** [comment]
OK, I had export LANG and LANGUAGE in my `.profile`.

**Comment by mirguest** [comment]
> hmm, weird that I get `en_GB`... and not US.

@andresailer, when you SSH to the lxplus, some of your local environment variables will be passed to the server. It can be checked by adding `-v` to the SSH command.

**Comment by andresailer** [comment]
@mirguest Yes, that is also something to keep track of.
I had `en_US` on my local machine, and SendEnv in ssh, but the `.profile` on the target machine had LANG/LANGUAGE
