### ISSUE TITLE
HiggsAnalysis-CombinedLimit

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/key4hep-spack#172]
It would be nice to add this cms statistical tool:

https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit

I don't see it in upstream spack. shall we contact the developers suggesting them to maintain a recipe?

**Comment by clementhelsens** [comment]
Does someone has an idea on how to proceed?

**Comment by vvolkl** [comment]
Hi Clement, sorry, I forgot to respond here. The issue with this oneis that the cms dependencies are hardcoded: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit/blob/102x/Makefile#L25 I think it only makes sense to package it if the build system is rewritten. How urgent is this? It can still be run standalone, right?
