### ISSUE TITLE
Review spack as a replacement for iLCInstall

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#185]
The dependencies of the ilcsoft packages could probably be cleaned up a bit. Currently it looks like some packages also partially state the transitive dependencies (i.e. dependencies of their dependencies).

**Comment by vvolkl** [comment]
Do you have an example for this? I went through the `CMakeLists.txt` of the ilcsoft packages and added everything that was there as a `find_package` call. I think if it is explicitly set up in the cmake configuration, it should also be an explicit dependency in the spack recipe.

**Comment by tmadlener** [comment]
Actually, I think what I was referring to with this is that, e.g. all packages that depend on `marlin` would no longer need to depend on `ilcutil` because that is a dependency of `marlin` already. Similarly `marlinutil` depens on `marlin`, but in many packages both dependencies are listed. 

However, I think "mirroring" the `find_package` calls is actually the right thing to do, especially because spack might not bring the right environment up otherwise at build and runtime.

Additionally, I think I mainly opened this issue to not forget to have a "real" look into this at a later point (which obviously hasn't happened since).

**Comment by vvolkl** [comment]
- [x] transitive dependencies are ok when declared in the CMakeLists.txt 

I'm going to add a point then:

- [ ]  Installation of sources: the convention in iLCSoft seems to be to copy all source files to the installation prefix. In fact, some packages (fcalclusterer I think) won't even work without this. However, this can make problems when creating views. I guess all ilcsoft packages should have a variant `install_sources` where this can be turned on/off depending on use case

**Comment by vvolkl** [comment]
actually, I just noticed the option `spack install --source` - which will install the source tree to `<prefix>/share/<packagename>/src`. If that's an option, then  there are actually no changes necessary to the recipe. If it is necessary to install the sources to `<prefix>`, then that needs to be done in the recipe. Regarding the views, spack can ignore file conflicts, which will be inevitable in that case.

**Comment by tmadlener** [comment]
One more thing that is missing from the spack installation that is present when using iLCInstall is the `ILCSOFT` environment variable that usually points back to the root folder of the iLCSoft installation. For a spack installation this doesn't really make sense though, because the `ilcsoft` bundle package essentially consists only of the setup script in the end.

One of the main uses of `$ILCSOFT` is finding the `ILCSoft.cmake` script that can be used to pre-configure some common cmake settings (e.g. c++ standard) and help cmake find other iLCSoft packages. I am not sure if this is a particularly serious problem in the end, since spack sets up the proper `CMAKE_PREFIX_PATH` in any case, so the only thing that is missing are the common settings. These will have to be set manually when building ilcsoft packages on top of a spack installation.

**Comment by vvolkl** [comment]
Yes, sounds like spack makes `ILCSoft.cmake`obsolete - the settings you describe would go into a spack environment. If you want to have it in order to more completely reproduce ilcinstall behavior, I'd suggest to add it to the ILCSoft bundle package, and install it from the `package.py`, like:

```
  ilcsoft_cmake = join_path(os.path.dirname(__file__), 'ILCSoft.cmake')
  install(ilcsoft_cmake, self.prefix)
```
Then you can also set `$ILCSOFT` from there.

**Comment by vvolkl** [comment]
@tmadlener I think we can close this after the spack ilcsoft build discussed today is successful?

**Comment by tmadlener** [comment]
Yes, I agree. The installed software seems to be working as intended (and the same) regardless of how it is installed. Having an exact replication of the installed tree is probably not possible in any case, due to the in-source build of iLCInstall.
