### ISSUE TITLE
Build break on ddhep4 included packages

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#190]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

This is also breaking with marlinutils

What appears to be happening is that there is a missing input value for  CXX_STANDARD environment values so that cmake concats with the next keyword

 - OS version: mageia
 - Compiler version: GCC 10.2
 - Package version: tag or commit ID, or GitHub branch HEAD - 2020407
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (ROOT versions, LCG release), cmake, build, run...

http://dev1.bitquant.com.hk:8011/#/builders/3/builds/1332/steps/2/logs/stdio
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve
```
2 errors found in build log:
     82      try_compile given unknown argument "False".
     83    Call Stack (most recent call first):
     84      /opt/spack/linux-mageia9-broadwell/gcc-10.2.0/dd4hep-1.16.1-s7csflmayxymlr5fxxecdlfcm4my6ikb/cmake/DD4hepConfig.cmake:53 (DD4HEP_SETUP_BOOST_TARGETS)
     85      CMakeLists.txt:42 (FIND_PACKAGE)
     86    This warning is for project developers.  Use -Wno-dev to suppress it.
     87    
  >> 88    CMake Error at /tmp/user/spack-stage/spack-stage-marlinutil-1.15.1-xs4kridani4mb72de7uhhf3eybj63tpb/spack-build-xs4krid/try/CMakeFiles/CMakeTmp/CMakeLists.txt:14 (add_executable):
     89      CXX_STANDARD is set to invalid value 'CXX_EXTENSIONS'
     90    
     91    
  >> 92    CMake Error at /opt/spack/linux-mageia9-broadwell/gcc-10.2.0/dd4hep-1.16.1-s7csflmayxymlr5fxxecdlfcm4my6ikb/cmake/DD4hepBuild.cmake:759 (try_compile):
     93      Failed to generate test project build system.
     94    Call Stack (most recent call first):
     95      /opt/spack/linux-mageia9-broadwell/gcc-10.2.0/dd4hep-1.16.1-s7csflmayxymlr5fxxecdlfcm4my6ikb/cmake/DD4hepConfig.cmake:53 (DD4HEP_SETUP_BOOST_TARGETS)
     96      CMakeLists.txt:42 (FIND_PACKAGE)
     97    
     98    
```

**Comment by vvolkl** [comment]
This is quite strange, as CMAKE_CXX_STANDARD is definitely set by DD4HEP:
https://github.com/AIDASoft/DD4hep/blob/4df3c2f6f26ca7fac19fbefebf3fdbf9b47de2c0/CMakeLists.txt#L51

what standard are you using for your test builds?

**Comment by vvolkl** [comment]
ok, so it is set by dd4hep, but not necessarily by downstream packages. Seems to be fixed by explicitly adding CMAKE_CXX_STANDARD in the recipe for those. @joequant are you using upstream spack or the key4hep fork for this?

**Comment by andresailer** [comment]
Which version of cmake is being used here? I am wondering if the complaint is new. Because the packages were built before without complaint, right? So maybe something we need to fix in DD4hep.

**Comment by joequant** [comment]
Using key4hep fork.

Also I think most of the packages are fixed, but marlinutil is still missing the define.  Can you add it there?

**Comment by joequant** [comment]
These packages are failing:
* marlinutil
* aidatt
* marlindd4hep

The version of cmake I am using is 3.20.1 compiled internally

**Comment by vvolkl** [comment]
This is already fixed by explicitly setting the CMAKE_CXX_STANDARD for the concerned packages. There is also an upstream fix: https://github.com/AIDASoft/DD4hep/pull/899
