### ISSUE TITLE
Build break: Gaudi, when using glibc > 2.31

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#191]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

issue is that glibc 2.32 has removed sys_siglist and has been replaced by strsignal

 - OS version: mageia
 - Compiler version: GCC 10.2
 - Package version: tag or commit ID, or GitHub branch: HEAD - 2020407
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (ROOT versions, LCG release), cmake, build, run...
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve

Full run at http://dev1.bitquant.com.hk:8011/#/builders/3/builds/1332/steps/2/logs/stdio

```
/tmp/user/spack-stage/spack-stage-gaudi-35.0-b2evjsi4dpl6dliiseqqazl6jzo3ulk6/spack-src/GaudiUtils/src/component/SignalMonitorSvc.cpp: In function 'const char* {anonymous}::sig_desc(int)':
/tmp/user/spack-stage/spack-stage-gaudi-35.0-b2evjsi4dpl6dliiseqqazl6jzo3ulk6/spack-src/GaudiUtils/src/component/SignalMonitorSvc.cpp:205:12: error: 'sys_siglist' was not declared in this scope
  205 |     return sys_siglist[signum];
      |            ^~~~~~~~~~~
```

**Comment by vvolkl** [comment]
This one can be patched quite easily, see https://gitlab.cern.ch/gaudi/Gaudi/-/issues/175

**Comment by vvolkl** [comment]
Fixed in gaudi master. I'll keep this open until I have added a patch for older versions
