### ISSUE TITLE
gcc10: Build Break KKMCEE - Real / complex type mismatch in Fortran 2018

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#192]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: mageia
 - Compiler version: GCC 10.2
 - Package version: tag or commit ID, or GitHub branch: HEAD 20210408
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (ROOT versions, LCG release), cmake, build, run...
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve

http://dev1.bitquant.com.hk:8011/#/builders/3/builds/1332/steps/2/logs/stdio``

KKMCee is breaking because of a type mismatch in Fortran 2018

```
make[2]: Leaving directory '/tmp/user/spack-stage/spack-stage-KKMCee-4.30-a2zlmgybulsi4qm5w7ctyibryumqy26a/spack-src/bornv'
bhang4_640.f:1658:44:

  481 |      +   (RMIN,BOUNDH,H,REPS,AEPS,BHAHRD,RR,HRD,AIHH,AIHA)
      |                                         2   
......
 1658 |          CALL SIMPS(A,B,H,REPS1,AEPS1,BHAL1,X,SI,AIHH,AIHA)
      |                                            1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (COMPLEX(8)/REAL(8)).
bhang4_640.f:1661:44:
```

A possible quick fix will be to add -fallow-argument-mismatch to FFLAGS, or use std=legacy, but this is discouraged

**Comment by vvolkl** [comment]
Thanks for the upstream bug report! I'm fine with adding a flag to allow compilation though.
