### ISSUE TITLE
Compilers.yaml points to clang in CVMFS, but its not there

### ISSUE THREAD

**Issue by fdplacido** [key4hep/key4hep-spack#228]
The compilers file:
https://github.com/key4hep/key4hep-spack/blob/release/environments/key4hep-common/compilers.yaml

points to the clang compiler, but the `llvm` folder is not there yet.

**Comment by vvolkl** [comment]
Thanks for the report - the release build which publishes this also failed until now because of a few small issues, now it should be there.
