### ISSUE TITLE
Performance issues with `spack dev-build` in CI

### ISSUE THREAD

**Issue by vvolkl** [key4hep/key4hep-spack#234]
`spack dev-build` would have some advantages to offer for CI jobs, as it is more flexible and configurable wrt. a view, and also avoids picking up old versions of the package being built from the view (it could try to compile all dependencies from scratch, but that can be avoided with a careful spack setup). 

However, I've seen that it performs quite badly in our typical ci jobs, for example this one:

https://github.com/key4hep/k4FWCore/pull/51/checks

took 43 min compared to 2 min 40s for the jobs using the view, which do essentially the same thing. There is some expected overhead due to the concretization, but that should be about a minute or less. In other jobs I have also seen spack-dev build jobs fail due to running out of disk space. This could indicate that spack does something different in terms of accessing the dependencies installed on CVMFS, which leads to the machine trying to cache unnecessary files.

I'll remove the spack configuration in the key4hep repositories, and set up a test repo to investigate this further.

**Comment by jmcarcell** [comment]
Closing stale issue
