### ISSUE TITLE
babayaga: warning indicating floating point exception

### ISSUE THREAD

**Issue by vvolkl** [key4hep/key4hep-spack#261]
```
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO IEEE_DENORMAL
```
Seems to be an issue with compilers newer than gcc4.7.

**Comment by jmcarcell** [comment]
It doesn't seem to be the case for the current builds on centos7 and ubuntu anymore, closing...

**Comment by vvolkl** [comment]
This is  still present in the latest release on lxplus. It's a runtime issue (try running `babayaga`). It's not necessarily the highest priority, but maybe  good to keep open to keep track of it.

**Comment by jmcarcell** [comment]
Ah I didn't know it was a runtime one. I also get it

**Comment by jmcarcell** [comment]
I contacted the authors and the warnings are harmless; nevertheless there is a fix to silence it the next time babayaga is included in the nightlies (when hepforge.org is back up again...)
