### ISSUE TITLE
Add Sherpa 2.2.11 to the stack

### ISSUE THREAD

**Issue by gganis** [key4hep/key4hep-spack#289]
We got requests for using Sherpa from the stack for FCC-ee.
Could the latest 2 version (2.2.11) be added?

**Comment by vvolkl** [comment]
With or without openmip support (or both)?

**Comment by gganis** [comment]
Ideally both, but let's start with the without first ... Thanks!

**Comment by vvolkl** [comment]
Sherpa is now in the stack ( currently v2.2.12 ).
