### ISSUE TITLE
packages not picking up py-jinja2 dependecy though podio

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#319]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

Getting failures in several packages as they are not picking up jinja2 dependence through podio

This happening in fcc-emd and edm4hep

It can be fixed by adding a py-jinja2 dependence through those packages but do not understand why its not picking it up thorugh podio

==> Error: ProcessError: Command exited with status 1:
    'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/edm4hep-master-gzyaucnh7lgrnt2zibrhltccjqyumrrx' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' '-DCMAKE_INSTALL_RPATH:STRING=/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/edm4hep-master-gzyaucnh7lgrnt2zibrhltccjqyumrrx/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/edm4hep-master-gzyaucnh7lgrnt2zibrhltccjqyumrrx/lib64;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/root-6.24.06-ezjmgbwqfbkxbkx7mpx52k6jiwq6yiml/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxml2-2.9.12-hcjqkgnod4ohul7ejdbnchoxi5grabwg/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libiconv-1.16-544aqkfhebsztcgsh4xtcilt6a6aiext/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xz-5.2.5-t2yqem2m3j4uacp7grzthnjkar462q5t/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/zlib-1.2.11-prrzh7wvh7q5cfbjdtdv4fp7sndjgd6i/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/openssl-1.1.1m-nmassjm3bbbnxzalflf65b57wefemaf6/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/util-linux-uuid-2.36.2-zqd364hhn7nn7e3ts3ll7fn7nbobapog/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/freetype-2.11.0-ecucsdgpa4oqchhynv3ord7zvw6s7xxi/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/bzip2-1.0.8-fdh66qwv6rp3447pnatq24e4akz6p4bz/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libpng-1.6.37-y52ld5zoyoe3b74wagprzmw7uxzufa7q/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/ftgl-2.4.0-5b5x3quapojk2ch3dskffhgymjaxuohv/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/mesa-21.3.1-xccmiisinzkma2koevlrxq6g7kyg756l/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/expat-2.4.3-v6nq5l57f7orhc6ktqkd5x6vwkukc6x3/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libbsd-0.11.3-thsyhwmryvlhfvyukzqszlt5d7u5x3kz/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libmd-1.0.3-osquudh4qotu5msiaanxraq6lqvayxlm/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/glproto-1.4.17-xt32klor4a73i6dchhzcrh67m63wyt47/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libunwind-1.5.0-p5btnasuysgxhqkdpnaorxz56ji4scgw/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libx11-1.7.0-bqbbvznllwxcxy6noncqsugetv564jrs/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/inputproto-2.3.2-rjxpaovvr62brva37gspfnvvzek5kagk/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/kbproto-1.0.7-xgocoktiy2nd7xeab2mqjkdnuthznvhx/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxcb-1.14-okdgg4iuseqt7pp4shzeq64z34emx4jh/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libpthread-stubs-0.4-dnorrdyapu2ndiptb7cij2d3tls3tupb/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxau-1.0.8-oaqg56gz4xxuuwaq4jdmjiwig5hkeekz/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xproto-7.0.31-32liqfllalstuewakksalzvps23fh7bc/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxdmcp-1.1.2-t6keqqslyiah446rao4zku75aoutyto5/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xcb-proto-1.14.1-3zys2kj44eftixbr4uov6hm7srmuosyf/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xextproto-7.3.0-fmlrnpj5mdiqykxbh47nbnxxammoxpog/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxext-1.3.3-wq2inchtd2h2yoiumwkxypxrskvzkd3m/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxt-1.1.5-iwogxfadagt5g2bqzw3xeygjt76ekwx5/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libice-1.0.9-oqjdhyexenaodtjciijik37iflwbkcjv/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libsm-1.2.3-oruaoe2n4ulbi5sydsleneesipbrznyw/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxrandr-1.5.0-w6ugaaivpx7bxnzvyp2uxr3nopfy5nkg/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxrender-0.9.10-sw3rcufngc5u5yan6vfxu6ad3epsk3mx/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/renderproto-0.11.1-xua6v42bfu26at7fyollvkhuajuom6hm/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/randrproto-1.5.0-cowqtuqdok7a3v3ls6njrhu2cvlp45ry/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/mesa-glu-9.0.1-vfsigzgvf5iso4ljlqltiy3hi4ql6kal/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/gl2ps-1.4.2-4fi4boj2pub56t4yoy4ir6vrkhjsd245/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxi-1.7.6-rnj437e34eoo6w4d4zktv57fyl7bifur/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/fixesproto-5.0-2qcpepyehai37l63y7xaqbk2hii3pmsq/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxfixes-5.0.2-xqkgmkwo5kmtcpzagqss3m4ijx2cqvct/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxxf86vm-1.1.4-alqp6zolueanwrlr4kdb23fhuar5v2ig/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xf86vidmodeproto-2.3.1-cir45ba3jmhy7svz6dqlhysmljuevdp2/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libdrm-2.4.100-s6xbbsxcidgigas63shsdlqyf5fiv2hq/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libpciaccess-0.16-u752y4p2ryyngyky4eunc6dgmtt7klqc/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxdamage-1.1.4-vgqoeds7qmpabemxwc23rgd5djyah3du/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/damageproto-1.2.1-ir6px7btzyciwp73xtegkiriss5cafnn/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxmu-1.1.2-bgxsg5ozi7x7mxaz4yoo7uehozniy2ue/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/gsl-2.7-usimj6dog7ixjmm6hn4fb436v3iaqo4t/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/intel-tbb-2020.3-zel2lc7hnikldkkcdk7h562x6n23dfmn/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxft-2.3.2-yaajy5ixwolsbf7s4yhaiwhrmkxcs5ml/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/fontconfig-2.13.94-efz7fkqzgmpamoub3drdlke343u33rva/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/font-util-1.3.2-x5dca567ku6dlimm6tiuasb5643bxc6q/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxpm-3.5.12-jkgti7ha5rtdxfqjvql4en5n7ctyiftk/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/gettext-0.21-nvvy3lr7yqx762dff5i654ekwsegxkdj/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/ncurses-6.2-u5r5rasl2mbg6ujabpnjolikmmhxicpu/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/lz4-1.9.3-malotmkgociap2eblyelpjd3ngt4cxzx/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/openblas-0.3.19-h3pzaqvgl5cirlo7bqixu77pf4x5p6nr/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/pcre-8.44-35tokl3tlhug2ydtxvxumtez2jeqqg5p/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/unuran-1.8.1-gkvzhhqdeat65ofgpmhjgckcm4c3tw4k/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/rngstreams-1.0.1-qqp4mydrcjbdgu2q266pfh52gr3foelq/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/vdt-0.4.3-iquvnqag4tlitiacoy64haroj7fo4rce/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xxhash-0.8.0-b4zklatnrjyx7idbj5ixbg5doasb6uvb/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/zstd-1.5.0-5t7bopc6rnxik35gsd5l7qp2tftnckwp/lib;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/podio-0.14-ohpjxro3mntkpzqwy4i6thn7jrx34gfq/lib64;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/davix-0.7.6-kbgnodxk4ut7pnp7aai3o5dnqvlchqkm/lib64;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/freeglut-3.2.1-qwbgxww7g6ztrsymsv7sa5dnmhc7de4m/lib64;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/glew-2.1.0-w6kki2utydgfncztq3kzrgj4khrs5qg3/lib64;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libjpeg-turbo-2.1.0-z3zpj6k47desa2bk3hlbcjdzixyghp4p/lib64;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/nlohmann-json-3.10.4-awopcwt5hqqq3ixxvdlh7w2lofwmhtkt/lib64' '-DCMAKE_PREFIX_PATH:STRING=/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/podio-0.14-ohpjxro3mntkpzqwy4i6thn7jrx34gfq;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/root-6.24.06-ezjmgbwqfbkxbkx7mpx52k6jiwq6yiml;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/zstd-1.5.0-5t7bopc6rnxik35gsd5l7qp2tftnckwp;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xxhash-0.8.0-b4zklatnrjyx7idbj5ixbg5doasb6uvb;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/vdt-0.4.3-iquvnqag4tlitiacoy64haroj7fo4rce;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/unuran-1.8.1-gkvzhhqdeat65ofgpmhjgckcm4c3tw4k;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/rngstreams-1.0.1-qqp4mydrcjbdgu2q266pfh52gr3foelq;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/pcre-8.44-35tokl3tlhug2ydtxvxumtez2jeqqg5p;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/openblas-0.3.19-h3pzaqvgl5cirlo7bqixu77pf4x5p6nr;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/nlohmann-json-3.10.4-awopcwt5hqqq3ixxvdlh7w2lofwmhtkt;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/lz4-1.9.3-malotmkgociap2eblyelpjd3ngt4cxzx;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxpm-3.5.12-jkgti7ha5rtdxfqjvql4en5n7ctyiftk;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxft-2.3.2-yaajy5ixwolsbf7s4yhaiwhrmkxcs5ml;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/fontconfig-2.13.94-efz7fkqzgmpamoub3drdlke343u33rva;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/font-util-1.3.2-x5dca567ku6dlimm6tiuasb5643bxc6q;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libjpeg-turbo-2.1.0-z3zpj6k47desa2bk3hlbcjdzixyghp4p;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/intel-tbb-2020.3-zel2lc7hnikldkkcdk7h562x6n23dfmn;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/gsl-2.7-usimj6dog7ixjmm6hn4fb436v3iaqo4t;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/glew-2.1.0-w6kki2utydgfncztq3kzrgj4khrs5qg3;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/gl2ps-1.4.2-4fi4boj2pub56t4yoy4ir6vrkhjsd245;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxmu-1.1.2-bgxsg5ozi7x7mxaz4yoo7uehozniy2ue;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxdamage-1.1.4-vgqoeds7qmpabemxwc23rgd5djyah3du;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/damageproto-1.2.1-ir6px7btzyciwp73xtegkiriss5cafnn;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libdrm-2.4.100-s6xbbsxcidgigas63shsdlqyf5fiv2hq;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libpciaccess-0.16-u752y4p2ryyngyky4eunc6dgmtt7klqc;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/freeglut-3.2.1-qwbgxww7g6ztrsymsv7sa5dnmhc7de4m;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxxf86vm-1.1.4-alqp6zolueanwrlr4kdb23fhuar5v2ig;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xf86vidmodeproto-2.3.1-cir45ba3jmhy7svz6dqlhysmljuevdp2;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxi-1.7.6-rnj437e34eoo6w4d4zktv57fyl7bifur;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxfixes-5.0.2-xqkgmkwo5kmtcpzagqss3m4ijx2cqvct;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/fixesproto-5.0-2qcpepyehai37l63y7xaqbk2hii3pmsq;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/ftgl-2.4.0-5b5x3quapojk2ch3dskffhgymjaxuohv;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/mesa-glu-9.0.1-vfsigzgvf5iso4ljlqltiy3hi4ql6kal;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/mesa-21.3.1-xccmiisinzkma2koevlrxq6g7kyg756l;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xrandr-1.5.0-d7xydjr276s642kx77cncarffrnmwh42;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxrandr-1.5.0-w6ugaaivpx7bxnzvyp2uxr3nopfy5nkg;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/randrproto-1.5.0-cowqtuqdok7a3v3ls6njrhu2cvlp45ry;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxrender-0.9.10-sw3rcufngc5u5yan6vfxu6ad3epsk3mx;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/renderproto-0.11.1-xua6v42bfu26at7fyollvkhuajuom6hm;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxt-1.1.5-iwogxfadagt5g2bqzw3xeygjt76ekwx5;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libsm-1.2.3-oruaoe2n4ulbi5sydsleneesipbrznyw;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libice-1.0.9-oqjdhyexenaodtjciijik37iflwbkcjv;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxext-1.3.3-wq2inchtd2h2yoiumwkxypxrskvzkd3m;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libx11-1.7.0-bqbbvznllwxcxy6noncqsugetv564jrs;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xtrans-1.3.5-k3nizi7kglck5qgteiq3v44fjbbgul2q;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xextproto-7.3.0-fmlrnpj5mdiqykxbh47nbnxxammoxpog;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxcb-1.14-okdgg4iuseqt7pp4shzeq64z34emx4jh;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xcb-proto-1.14.1-3zys2kj44eftixbr4uov6hm7srmuosyf;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxdmcp-1.1.2-t6keqqslyiah446rao4zku75aoutyto5;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxau-1.0.8-oaqg56gz4xxuuwaq4jdmjiwig5hkeekz;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xproto-7.0.31-32liqfllalstuewakksalzvps23fh7bc;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libpthread-stubs-0.4-dnorrdyapu2ndiptb7cij2d3tls3tupb;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/kbproto-1.0.7-xgocoktiy2nd7xeab2mqjkdnuthznvhx;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/inputproto-2.3.2-rjxpaovvr62brva37gspfnvvzek5kagk;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libunwind-1.5.0-p5btnasuysgxhqkdpnaorxz56ji4scgw;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/glproto-1.4.17-xt32klor4a73i6dchhzcrh67m63wyt47;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/freetype-2.11.0-ecucsdgpa4oqchhynv3ord7zvw6s7xxi;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libpng-1.6.37-y52ld5zoyoe3b74wagprzmw7uxzufa7q;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/davix-0.7.6-kbgnodxk4ut7pnp7aai3o5dnqvlchqkm;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/python-3.9.9-xcgn3tl5plllisk3xwt7i3ewuqylwvra;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/util-linux-uuid-2.36.2-zqd364hhn7nn7e3ts3ll7fn7nbobapog;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/gettext-0.21-nvvy3lr7yqx762dff5i654ekwsegxkdj;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/tar-1.34-u6g5vvfnfko3cuny42a74vwjidec4mdk;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libxml2-2.9.12-hcjqkgnod4ohul7ejdbnchoxi5grabwg;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/xz-5.2.5-t2yqem2m3j4uacp7grzthnjkar462q5t;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/expat-2.4.3-v6nq5l57f7orhc6ktqkd5x6vwkukc6x3;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libbsd-0.11.3-thsyhwmryvlhfvyukzqszlt5d7u5x3kz;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libmd-1.0.3-osquudh4qotu5msiaanxraq6lqvayxlm;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/cmake-3.22.1-bolio7gg7c2rv2tm4x7nkm3vgtk364uy;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/openssl-1.1.1m-nmassjm3bbbnxzalflf65b57wefemaf6;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/zlib-1.2.11-prrzh7wvh7q5cfbjdtdv4fp7sndjgd6i;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/bzip2-1.0.8-fdh66qwv6rp3447pnatq24e4akz6p4bz;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/libiconv-1.16-544aqkfhebsztcgsh4xtcilt6a6aiext;/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/ncurses-6.2-u5r5rasl2mbg6ujabpnjolikmmhxicpu' '-DCMAKE_CXX_STANDARD:STRING=17' '-DBUILD_TESTING:BOOL=OFF' '/tmp/user/spack-stage/spack-stage-edm4hep-master-gzyaucnh7lgrnt2zibrhltccjqyumrrx/spack-src'
1 error found in build log:
     37    -- Detected GNU compatible linker
     38    -- Creating 'edm4hep' datamodel
     39    Traceback (most recent call last):
     40      File "/opt/spack/linux-mageia9-broadwell/gcc-11.2.1/podio-0.14-ohp
           jxro3mntkpzqwy4i6thn7jrx34gfq/python/podio_class_generator.py", line
            23, in <module>
     41        import jinja2
     42    ModuleNotFoundError: No module named 'jinja2'
  >> 43    CMake Error at /opt/spack/linux-mageia9-broadwell/gcc-11.2.1/podio-0
           .14-ohpjxro3mntkpzqwy4i6thn7jrx34gfq/lib64/cmake/podio/podioMacros.c
           make:159 (message):
     44      Could not generate datamodel 'edm4hep'.  Check your definition in
     45      '../edm4hep.yaml'
     46    Call Stack (most recent call first):
     47      edm4hep/CMakeLists.txt:4 (PODIO_GENERATE_DATAMODEL)
     48    
     49    
See build log for details:
  /tmp/user/spack-stage/spack-stage-edm4hep-master-gzyaucnh7lgrnt2zibrhltccjqyumrrx/spack-build-out.txt

 - OS version: mageia
 - Compiler version: GCC11
 - Package version: tag or commit ID, or GitHub branch
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (ROOT versions, LCG release), cmake, build, run...
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve

**Comment by wdconinc** [comment]
I really wish this was somehow possible to express in spack. I don't actually understand why it happens, since dependencies are transitive and pyyaml and jinja2 are both run-type dependencies of podio, which presumably should extend to edm4hep.

**Comment by vvolkl** [comment]
They do extend to edm4hep as run-time dependencies, which aren't available in the build phase when cmake calls the podio generator python script. You could make it happen in a `setup_dependent_build_environment` in podio, but it seems like adding those two packages directly as build dependencies is easier (at least once you know).
