### ISSUE TITLE
Cancelled and restarted CI workflows running spack install can get stuck trying to aquire a look

### ISSUE THREAD

**Issue by vvolkl** [key4hep/key4hep-spack#335]
Similar to what is discussed here:
https://github.com/spack/spack/issues/9166

Simplest workaround is to manually remove the locks (<prefix>/.spack/lock)

**Comment by jmcarcell** [comment]
This hasn't happened for me recently but builds are now done in containers so the locks are new every time the workflow is restarted, closing...
