### ISSUE TITLE
Latest key4hep release seems to be broken, cannot build against it

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#336]
The CI runs for, e.g. podio that have already picked up the latest release seem to be broken because they pick an unsuitable `as` installation (specifically it looks like the one from the underlying system is picked).

See, e.g. here:
https://github.com/AIDASoft/podio/runs/5750929183?check_suite_focus=true#step:4:221

It is possible that this surfaces only in the CI containers, or that we simply miss putting `as` (i.e. `binutils`) into the environment. Alternatively, it could also be possible that it is `gcc-11` that passes new flags to `as` in the build process that were not used before.

**Comment by tmadlener** [comment]
Looks like spack builds `gcc ~binutils` by default. I briefly checked an LCG release and they ship their own binutils.

**Comment by vvolkl** [comment]
My bad, I did install gcc+binutils for gcc8, but that got lost along the way. Rebuilding gcc with binutils now.

**Comment by tmadlener** [comment]
Thanks

**Comment by vvolkl** [comment]
Actually, just adding binutils to the setup script seems to fix this (which is also how the build machine was setup). Additionally, the setup script generation was missing LD_LIBRARY_PATH and LIBRARY_PATH for gcc, which is still required to find the right libstdc++.so. I've patched both in the setup script, and the builds using the latest release seem to be ok now. Could you restart the workflow?

**Comment by tmadlener** [comment]
Looks like some runs have already picked up the fixes, and everything is working again:
https://github.com/AIDASoft/podio/actions/runs/2065060131

**Comment by tmadlener** [comment]
The breaking changes in podio seem to be introduced with AIDASoft/podio#254 (but not yet in AIDASoft/podio#253). I have to check what the actual problem is. Also considering that those two PRs are essentially formatting changes.

**Comment by vvolkl** [comment]
```
Warning in <TInterpreter::ReadRootmapFile>: class  edm4hep::ObjectID found in libedm4hepDict.so  is already in libedm4drDict.so 
```
libedm4drDict.so is new in this release: It is build in the latest version of the dual-readout package:  https://github.com/HEP-FCC/dual-readout/tree/master/edm4dr

However, we still have fcc-edm in the stack, so two podio-based datamodels in the same environment should in theory be ok to coexist.

**Comment by tmadlener** [comment]
The problem with the dual-readout EDM is that it redefines `edm4hep::ObjectID`. However, even if I manually remove that from `LD_LIBRARY_PATH`, I can get rid of the warning but the segmentation fault persists. Maybe I have to remove it from `ROOT_INCLUDE_PATH` as well?

The offending commit in podio is the one that fixes the clang-tidy flagged issues.

**Comment by tmadlener** [comment]
There seem to be a few more thing that are not yet as with the old release:

- tricktrack seems to be missing from the `CMAKE_PREFIX_PATH`: https://github.com/tmadlener/EDM4hep/runs/5774262297?check_suite_focus=true#step:4:213
- `vdt` seems to not appear on the necessary list of include paths: https://github.com/tmadlener/EDM4hep/runs/5774262297?check_suite_focus=true#step:4:285
  - This one is arguably actually a ROOT bug, because somewhere in the ROOT internals the `vdt` target isn't properly forwarded if an external `vdt` is used. I have run into this before, but I haven't yet been able to conclusively track it down, or to come up with a simple reproducer that could be used in a bug report. However, this has been working with earlier key4hep releases, so I assume that something in a previous release was either masking this or fixing it in some other way.

Everything still works with the nightlies that are still using the older release setup it seems: https://github.com/tmadlener/EDM4hep/runs/5774262370?check_suite_focus=true

**Comment by jmcarcell** [comment]
Closing as this is old and not relevant anymore
