### ISSUE TITLE
build errors on gcc10

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#35]
I'm getting build errors trying to build on gcc10.  There are compiler failures on 

edm4hep and fcc-edm

would appreciate some help in figuring out to make these build

[spack.log](https://github.com/key4hep/k4-spack/files/5153580/spack.log)

**Comment by andresailer** [comment]
@tmadlener Can you have a look at the error message for fcc-edm, is that because of fcc-edm not working with the latest podio?

**Comment by andresailer** [comment]
@joequant as there are warnings from parsing the edm4hep.yaml, maybe you need to pull the latest edm4hep commits? 
Are you building the HEAD versions or tags?

**Comment by tmadlener** [comment]
It looks like podio is emitting a deprecation warning when generating the files for fcc-edm. But these should still work fine in this case. I am not entirely sure why `fcc-edm` still emits compiler errors, complaining about not being able to find some generated components.
@joequant can you have a look inside the build folder generated by spack whether these components are generated?

Then there is a second error as @andresailer has already mentioned, that looks like `edm4hep` is not fully up to date. Can you check which version of `edm4hep` spack would be using in this case?

**Comment by tmadlener** [comment]
@joequant I have opened #36, can you check if that fixes the problem with `edm4hep` in your case?

**Comment by joequant** [comment]
Thanks!!! Will check it out tomorrow.

**Comment by joequant** [comment]
#36 and also setting key4hep-stack to 0.2.0 fixes edm4hep

However, fcc-edm is still broken even after podio is set to 0.2.0

**Comment by tmadlener** [comment]
Hi @joequant 

> setting key4hep-stack to 0.2.0 fixes edm4hep

Sorry, I am not entirely sure I get what you mean here. Do you mean doing something like `key4hep@0.2.0`, or do you mean fixing the [package.py](https://github.com/key4hep/k4-spack/blob/master/packages/key4hep-stack/package.py) in some way?

Can you post the output of `spack spec fcc-edm` here? Just so see which versions of the packages actually get concretized. I suppose the build error is still the same as without #36?

**Comment by tmadlener** [comment]
I just saw that you have opened #39. Does that fix the `fcc-edm` problem for you?

**Comment by vvolkl** [comment]
Thanks for checking the recipes with gcc10! I think increasing the version of the bundle-package was an accidental workaround, because some constraints on the version numbers only apply for `when="@0.1"`. Looks to me like the problem was due to the new versions in podio and depending packages, not gcc 10. I merged the corresponding PRs, so I'm guessing this is fixed, @joequant , can you confirm that?
