### ISSUE TITLE
Request to add the "Rome" framework

### ISSUE THREAD

**Issue by andresailer** [key4hep/key4hep-spack#350]
* [ ] Request to add the "Rome" framework (from MEG experiment at PSI) for the IDEA DriftChamber simulation used in FCC reconstruction
    * https://github.com/lialavezzi/DriftChamberPLUSVertex/tree/uptodate
        * depends on https://bitbucket.org/muegamma/rome3
    * Valentin trying to separate required functionality together with Lorenzo

**Comment by jmcarcell** [comment]
Is this still needed / relevant?

**Comment by jmcarcell** [comment]
It seems not
