### ISSUE TITLE
Clang build

### ISSUE THREAD

**Issue by andresailer** [key4hep/key4hep-spack#356]
* useful for sycl , oneapi, llvm in general

**Comment by vvolkl** [comment]
Did a test build with clang13, and found these residual issues:
#358 
#357

**Comment by vvolkl** [comment]
Fixed with #364 
https://gitlab.cern.ch/key4hep/k4-deploy/-/pipelines/3947611
Use with `source /cvmfs/sw.hsf.org/spackages5/key4hep-stack/2022-05-09/x86_64-centos7-clang13.0.0-opt/vw4xi/setup.sh
`
