### ISSUE TITLE
py-awkward no longer installs headers

### ISSUE THREAD

**Issue by vvolkl** [key4hep/key4hep-spack#361]
py-awkward no longer installs its headers, which are needed by FCCAnalyses.
Older installation: `/cvmfs/sw.hsf.org/spackages5/py-awkward/1.4.0/x86_64-centos7-gcc11.2.0-opt/43jqv/lib/python3.9/site-packages/awkward/`
Newer installation, missing headers: `/cvmfs/sw.hsf.org/spackages5/py-awkward/1.4.0/x86_64-centos7-gcc11.2.0-opt/kareq/lib/python3.9/site-packages/awkward/`

The version of py-awkward did not change between these installations, but the version of spack did - possibly connected to the change of `PythonPackage` to use pip.

**Comment by tmadlener** [comment]
I have run into this and the problem for me was connected to having a `python+debug` somewhere in the stack that made the awkward pip process put the headers in a different directory (which will not be installed). For me having `python~debug` solved the issue.

**Comment by vvolkl** [comment]
Thanks, I think that's it. I opened #362 since there are other reasons that make enforcing python~debug a good idea.

**Comment by jmcarcell** [comment]
`python~debug` is the default: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py#L119
