### ISSUE TITLE
Discussion: Organization of different releases / setup scripts

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#373]
As briefly discussed during the [Meeting on May 10](https://indico.cern.ch/event/1159169/) with more supported OSes and different compilers we might have to think about how we want to organize the "top-level" setup scripts that point to the latest releases.

Currently the `/cvmfs/sw.hsf.org/key4hep/setup.sh` simply picks up the latest release that has been built with gcc.

For specific releases one can always pick the dedicated setup script, e.g.
```sh
source /cvmfs/sw.hsf.org/spackages5/key4hep-stack/2022-04-25/x86_64-centos7-gcc11.2.0-opt/4652u/setup.sh
```

Since we are now starting to have releases with, e.g. clang (#356) and also on different OSes (#354), should we foresee to have easily accessible "latest" setup script for these as well? And if so, how should we organize them?

We could follow what the LCG releases are doing and sort of provide a an `<arch>-<os>-<compiler>` tuple under the `key4hep` directory. However, since we are not yet targetting different architectures we could potentially also keep this simpler.

**Comment by vvolkl** [comment]
Duplication of #372 ?

Copying from there:

By default, the setup script for any release is installed in the prefix of the release bundle package  in a directory like this:

```
/cvmfs/sw.hsf.org/spackages5/key4hep-stack/2022-05-09/x86_64-centos7-clang13.0.0-opt/vw4xi/setup.sh 
```
The gitlab pipeline will also create a directory called `latest`, symlinked to the most recent date, i.e.
`/cvmfs/sw.hsf.org/spackages5/key4hep-stack/latest -> /cvmfs/sw.hsf.org/spackages5/key4hep-stack/2022-05-09`
There is an even shorter shorthand, a script which sources the latest release with the binary tag `x86_64-centos7-gcc11.2.0-opt` and prints a few lines for information:
```
/cvmfs/sw.hsf.org/key4hep/setup.sh
#sources /cvmfs/sw.hsf.org/spackages5/key4hep-stack/latest/x86_64-centos7-gcc11.2.0-opt/*/setup.sh
```
One more alternative is to use `spack load key4hep-stack` with `/cvmfs/sw.hsf.org/spackages5` set up as an upstream.

Is this enough convenience, or is some tooling missing to better set up releases?

**Comment by tmadlener** [comment]
> Duplication of https://github.com/key4hep/key4hep-spack/issues/372 ?

Yes. Sorry. I was too slow with this one / didn't check if something appeared between starting it and submitting it. 

Feel free to close this one (or keep this one and close the other one).

**Comment by jmcarcell** [comment]
The setup has changed since the discussion started, now the packages are stored under
```
/cvmfs/sw-nightlies.hsf.org/key4hep/releases/<release>/<arch>-<os>-<compiler>-<opt/dbg>/
```

with symbolic links in

```
/cvmfs/sw-nightlies.hsf.org/key4hep/releases/latest-<opt/dbg>
```
to the latest release. The `setup.sh` script can source different releases.
