### ISSUE TITLE
a lot of setRead is not a member of DataObject

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#378]
In file included from /tmp/user/spack-stage/spack-stage-cepcsw-master-nl6hu2rdpywpmd7tcqj2lxcmnun3alme/spack-src/Reconstruction/Digi_Calo/src/CaloDigiAlg.h:4,
                 from /tmp/user/spack-stage/spack-stage-cepcsw-master-nl6hu2rdpywpmd7tcqj2lxcmnun3alme/spack-src/Reconstruction/Digi_Calo/src/CaloDigiAlg.cpp:2:
/opt/spack/linux-mageia9-zen2/gcc-12.0.1/k4fwcore-master-zq6s6m2mgyu2pvyix6m5m67grxet4sw4/include/k4FWCore/DataHandle.h: In instantiation of 'const T* DataHandle<T>::get() [with T = edm4hep::SimCalorimeterHitCollection]':
/tmp/user/spack-stage/spack-stage-cepcsw-master-nl6hu2rdpywpmd7tcqj2lxcmnun3alme/spack-src/Reconstruction/Digi_Calo/src/CaloDigiAlg.cpp:51:76:   required from here
/opt/spack/linux-mageia9-zen2/gcc-12.0.1/k4fwcore-master-zq6s6m2mgyu2pvyix6m5m67grxet4sw4/include/k4FWCore/DataHandle.h:142:48: error: 'setRead' is not a member of 'DataObjectHandle<DataWrapper<edm4hep::SimCalorimeterHitCollection> >'
  142 |       DataObjectHandle<DataWrapper<T>>::setRead();
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/opt/spack/linux-mageia9-zen2/gcc-12.0.1/k4fwcore-master-zq6s6m2mgyu2pvyix6m5m67grxet4sw4/include/k4FWCore/DataHandle.h:148:48: error: 'setRead' is not a member of 'DataObjectHandle<DataWrapper<edm4hep::SimCalorimeterHitCollection> >'
  148 |       DataObjectHandle<DataWrapper<T>>::setRead();
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /tmp/user/spack-stage/spack-stage-cepcsw-master-nl6hu2rdpywpmd7tcqj2lxcmnun3alme/spack-src/Digitisers/G2CDArbor/src/G2CDArborAlg.h:4,
                 from /tmp/user/spack-stage/spack-stage-cepcsw-master-nl6hu2rdpywpmd7tcqj2lxcmnun3alme/spack-src/Digitisers/G2CDArbor/src/G2CDArborAlg.cpp:1:
/opt/spack/linux-mageia9-zen2/gcc-12.0.1/k4fwcore-master-zq6s6m2mgyu2pvyix6m5m67grxet4sw4/include/k4FWCore/DataHandle.h: In instantiation of 'const T* DataHandle<T>::get() [with T = edm4hep::SimCalorimeterHitCollection]':
/tmp/user/spack-stage/spack-stage-cepcsw-master-nl6hu2rdpywpmd7tcqj2lxcmnun3alme/spack-src/Digitisers/G2CDArbor/src/G2CDArborAlg.cpp:503:44:   required from here
/opt/spack/linux-mageia9-zen2/gcc-12.0.1/k4fwcore-master-zq6s6m2mgyu2pvyix6m5m67grxet4sw4/include/k4FWCore/DataHandle.h:142:48: error: 'setRead' is not a member of 'DataObjectHandle<DataWrapper<edm4hep::SimCalorimeterHitCollection> >'
  142 |       DataObjectHandle<DataWrapper<T>>::setRead();
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/opt/spack/linux-mageia9-zen2/gcc-12.0.1/k4fwcore-master-zq6s6m2mgyu2pvyix6m5m67grxet4sw4/include/k4FWCore/DataHandle.h:148:48: error: 'setRead' is not a member of 'DataObjectHandle<DataWrapper<edm4hep::SimCalorimeterHitCollection> >'
  148 |       DataObjectHandle<DataWrapper<T>>::setRead();
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/opt/spack/linux-mageia9-zen2/gcc-12.0.1/k4fwcore-master-zq6s6m2mgyu2pvyix6m5m67grxet4sw4/include/k4FWCore/DataHandle.h: In instantiation of 'const T* DataHandle<T>::get() [with T = edm4hep::MCParticleCollection]':
/tmp/user/spack-stage/spack-stage-cepcsw-master-nl6hu2rdpywpmd7tcqj2lxcmnun3alme/spack-src/Digitisers/G2CDArbor/src/G2CDArborAlg.cpp:588:36:   required from here
/opt/spack/linux-mageia9-zen2/gcc-12.0.1/k4fwcore-master-zq6s6m2mgyu2pvyix6m5m67grxet4sw4/include/k4FWCore/DataHandle.h:142:48: error: 'setRead' is not a member of 'DataObjectHandle<DataWrapper<edm4hep::MCParticleCollection> >'
  142 |       DataObjectHandle<DataWrapper<T>>::setRead();

!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: mageia
 - Compiler version: GCC12
 - Package version: tag or commit ID, or GitHub branch: commit 26 May 2022

**Comment by wdconinc** [comment]
Simple remove of those offending lines is sufficient, https://eicweb.phy.anl.gov/EIC/juggler/-/merge_requests/417.

**Comment by joequant** [comment]
seems to be fixed in master
