### ISSUE TITLE
new spack seems to have moved PackageBase

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#396]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: mageia
 - Compiler version: gcc 12.
 - Package version: tag or commit ID, or GitHub branch 734bd8f9f8ee0b82765154e7cdd1d344513cef09
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (ROOT versions, LCG release), cmake, build, run...

spack install with most recent spack

from spack.package import PackageBase

seems to fail

```
  File "/home/joe/local2/bench/git/key4hep-spack/packages/key4hep-stack/package.py", line 11, in <module>
  File "/home/joe/local2/bench/git/key4hep-spack/packages/key4hep-stack/common.py", line 22, in <module>
    from spack.package import PackageBase
ImportError: cannot import name 'PackageBase' from 'spack.package' (/usr/lib/spack/spack/package.py)
```

**Comment by vvolkl** [comment]
Yes, this package is mostly used with the key4hep fork of podio (https://github.com/key4hep/spack) which we only update to the latest spack develop when needed/desired, and cherry-pick relevant changes otherwise. Thanks for checking though, it is good not to diverge too much.

**Comment by jmcarcell** [comment]
Fixed in https://github.com/key4hep/key4hep-spack/pull/397
