### ISSUE TITLE
tbb/lib[64] folders not in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by andresailer** [key4hep/key4hep-spack#413]
- Using the key4hep stacks for dd4hep CI builds. the tbb/lib (also for vecgeom) folder is not in the LD_LIBRARY_PATH leading to some test failures.
- e.g. https://github.com/AIDASoft/DD4hep/runs/7786855241?check_suite_focus=true#step:4:3211
- Not sure if this is from key4hep-spack, or spack?
- Now disabled TBB for the key4hep builds in DD4hep CI

**Comment by vvolkl** [comment]
This goes back to the configuration of the key4hep fork of spack, and can be fixed there. Not sure though why TBB isn't found via the RPATH, which should be set:  https://github.com/AIDASoft/DD4hep/blob/master/CMakeLists.txt#L83

**Comment by andresailer** [comment]
Yes, there is an rpath both for tbb and vecgeom in the executable for the test, but somehow the libraries are not loaded inside the test run

**Comment by andresailer** [comment]
Ahh, no, (at least some of) the installed test binaries do not have rpath anymore

**Comment by andresailer** [comment]
Ok, DD4hep side probably fixed with https://github.com/AIDASoft/DD4hep/pull/946/commits/e6a64ee6c11d078578b5693cf9905056ffb02b6c

**Comment by andresailer** [comment]
Also related key4hep/k4-project-template#12

**Comment by andresailer** [comment]
Resolved by setting rpath in respective packages
