### ISSUE TITLE
FCCAnalyses has a broken root dictionary or environment in the current nightly builds

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#439]
When trying to run the RDF tests for EDM4hep, there is an error about a fastjet header not being found:
https://github.com/key4hep/EDM4hep/actions/runs/3468095678/jobs/5793574524#step:4:588

Most likely this is just an issue with setting the run environment properly for fccanalyses

**Comment by vvolkl** [comment]
Please do, thanks! Which headers are missing?

**Comment by tmadlener** [comment]
See https://github.com/HEP-FCC/FCCAnalyses/issues/227
