### ISSUE TITLE
key4hep/setup.sh does not work in zsh

### ISSUE THREAD

**Issue by gartrog** [key4hep/key4hep-spack#459]
Hello,

Apologies if this is not the right repo to raise this issue, but I can't find where this file is located in the key4hep github repos...

The "main" setup.sh file `/cvmfs/sw.hsf.org/key4hep/setup.sh` used to work on both bash and zsh, but not anymore.

It is easy to fix, by replacing the first two lines:

```
setup_actual=$("ls" -t /cvmfs/sw.hsf.org/spackages6/key4hep-stack/*/x86_64-centos7-gcc11.2.0-opt/*/setup.sh)
setup_actual=$("echo" $setup_actual | "cut" --delimiter " " --fields 1)
```

by

```
setup_actual=$(ls -t1 /cvmfs/sw.hsf.org/spackages6/key4hep-stack/*/x86_64-centos7-gcc11.2.0-opt/*/setup.sh | head -n1)
```

which works on both bash and zsh.

**Comment by vvolkl** [comment]
Hello Nicolas,

thanks for the fix! Yes, this file is currently not deployed from this repo but it can be after the gitlab-runner on the publisher is in use.

I just published your change, should be there with a delay of max 10min.
