### ISSUE TITLE
Switch to non deprecated `py-onnxruntime` for stack

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#464]
Currently we build the stack using the `py-onnx-runtime` package which has been deprecated in favor of `py-onnxruntime`. I suppose this is a rather straight forward replacement, but I have to check it.

**Comment by tmadlener** [comment]
It looks like this is not yet part of any spack release and only available from `develop`

**Comment by jmcarcell** [comment]
Done
