### ISSUE TITLE
Error: name 'maintainers' is not defined

### ISSUE THREAD

**Issue by kkrizka** [key4hep/key4hep-spack#472]
- OS version: Alma Linux 9
 - Package version: `1fc911b` (`release` at the time of writing)
 - Reproduced by: [example running in gitlab CI](https://gitlab.cern.ch/kkrizka/mre-key4hep-spack-no-maintainers-error)
 - Goal: Trying to query/install package with the key4hep-spack repository added.

I am trying to test the work that @bartosik-hep started in porting the muon collider software to the key4hep stack. However I am having trouble using the latest version of the key4hep repository as any package queries (ie: `spack spec cmake`) give a `+==> Error: name 'maintainers' is not defined` error.

I've prepared an example of this here: [MRE Key4hep Spack No Maintainers Error](https://gitlab.cern.ch/kkrizka/mre-key4hep-spack-no-maintainers-error)

The TL;DR is that running

```shell
git clone --depth=1 --branch v0.19.1 https://github.com/spack/spack.git
source spack/share/spack/setup-env.sh
git clone https://github.com/key4hep/key4hep-spack
spack repo add key4hep-spack
spack spec cmake
```

ends with

```
+==> Error: name 'maintainers' is not defined
```

You can see the full output here: [key4hep-release](https://gitlab.cern.ch/kkrizka/mre-key4hep-spack-no-maintainers-error/-/jobs/29005774)
Everything works when running without the `key4hep-spack` repository: [vanilla](https://gitlab.cern.ch/kkrizka/mre-key4hep-spack-no-maintainers-error/-/jobs/29005772)
Or with an earlier ref of the repository: [key4hep-ec3ae6f](https://gitlab.cern.ch/kkrizka/mre-key4hep-spack-no-maintainers-error/-/jobs/29005774)

**Comment by jmcarcell** [comment]
I believe this has to do with a spack change where instead of being `maintainers = ["jmcarcell"]` now it is `maintainers("jmcarcell")` so `maintainers` has to exist for python not to complain about it. Can you try with spack 0.19.2, which is a release from two weeks ago? I don't thin we thought about these issues when we made the change to some packages but if it's not easy for you to change we can revert those changes and it should work fine with 0.19.1

**Comment by jmcarcell** [comment]
Indeed checking https://github.com/spack/spack/pull/35083/commits and checking out v0.19.1:
```
$ git show ab275e0711bf7bd9b6cd4128895cc37f4dcb0c5b
fatal: bad object ab275e0711bf7bd9b6cd4128895cc37f4dcb0c5b
```
so that didn't make it into v0.19.1

**Comment by kkrizka** [comment]
Thank you for the prompt entry

The v0.19.2 does not seem to have the ref either:
```
# git rev-parse HEAD
45accfac1584ca9c303b61a1f7e9097a3693a73e <- this is the HEAD of v0.19.2
# git show ab275e0711bf7bd9b6cd4128895cc37f4dcb0c5b
fatal: bad object ab275e0711bf7bd9b6cd4128895cc37f4dcb0c5b
```

I've added a test with v0.19.2 at [key4hep-release-spack-v0.19.2](https://gitlab.cern.ch/kkrizka/mre-key4hep-spack-no-maintainers-error/-/jobs/29008286) and it does fail with the same error. The test only seems to pass with the `develop` branch [key4hep-release-spack-develop](https://gitlab.cern.ch/kkrizka/mre-key4hep-spack-no-maintainers-error/-/jobs/29008287).

I don't believe we are tried to a specific version of spack as the transition is still in progress (@bartosik-hep should correct me). But it would be nice to stick to a released version.

**Comment by tmadlener** [comment]
This is most likely a change that only comes with spack 0.20, and the patches to 0.19 don't have these breaking changes.

**Comment by jmcarcell** [comment]
This should fix it: https://github.com/key4hep/key4hep-spack/pull/473

**Comment by tmadlener** [comment]
The problem with the fork approach is that someone has to maintain that fork and "catching" up with spack is quite a bit of work every few months. The new approach that we want to follow is to start from a spack tag and maintain a list of commits to cherry-pick onto that. This approach is also what the EIC folks are following. It has the advantage that all fixes have to land upstream first, which should effectively make small divergences between the fork and upstream impossible. Those were usually the most time-consuming to fix.

**Comment by vvolkl** [comment]
I don't see a big difference in this approach - you'll still need to agree on the list of commits to cherry-pick and sync those with everyone using key4hep-spack.

**Comment by jmcarcell** [comment]
#473 should have fixed this, please reopen if there are more problems @kkrizka
