### ISSUE TITLE
Enabling FFTW3 for ROOT

### ISSUE THREAD

**Issue by SanghyunKo** [key4hep/key4hep-spack#475]
Hi all, recently I realized that the current key4hep stack does not enable FFTW3 feature when building ROOT, unlike LCG one.
```bash
[sako@cms dual-readout]$ source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
Setting up the latest Key4HEP software stack from CVMFS ...
 ...  Key4HEP release: key4hep-stack/master-2023-03-23
 ... Use the following command to reproduce the current environment: 
 ... 
         source /cvmfs/sw-nightlies.hsf.org/spackages6/key4hep-stack/master-2023-03-23/x86_64-centos7-gcc11.2.0-opt/neioj/setup.sh
 ... 
 ... done. 
[sako@cms dual-readout]$ root-config --has-fftw3
no
```
We need this feature for the dual-readout calorimeter since we run some Fourier transforms during the reconstruction. Would it be possible to build ROOT with `-Dfftw3=ON`?

**Comment by SanghyunKo** [comment]
(please let me know before triggering the next nightly build, it'd be better to merge HEP-FCC/dual-readout#33 beforehand)

**Comment by jmcarcell** [comment]
Hi @SanghyunKo, this is available now in the latest nightly for centos7 and ubuntu
