### ISSUE TITLE
"Argument list too long" errors when setting up latest nightly build on condor 

### ISSUE THREAD

**Issue by bistapf** [key4hep/key4hep-spack#483]
Since today I'm experiencing issues with setting up the latest key4hep nightly build on condor. Locally (onl lxplus) things work fine. 

Submitting a job script that consists only of the line `source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh` results in the following error: 

`/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh: line 24: /usr/bin/cat: Argument list too long
/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh: line 24: /usr/bin/grep: Argument list too long`

The corresponding output log is: 

`Centos7 detected, will source the latest nightly for Centos7
Setting up the latest Key4HEP software stack from CVMFS ...
 ...  Key4HEP release: 2023-05-03
 ... Use the following command to reproduce the current environment: 
 ... 
         source /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-03/x86_64-centos7-gcc12.2.0-opt/key4hep-stack/2023-05-03-q6pq42/setup.sh
 ... `

I have attached also the detailed error log of this simple job (with `set -x`)
[condor_job.00000100249012500_error.txt](https://github.com/key4hep/key4hep-spack/files/11399011/condor_job.00000100249012500_error.txt)  as well as the job config 
[job_desc_lhep8_cfg.txt](https://github.com/key4hep/key4hep-spack/files/11399025/job_desc_lhep8_cfg.txt)
and script [job000001002_sh.txt](https://github.com/key4hep/key4hep-spack/files/11399063/job000001002_sh.txt) - both as generated by [the EventProducer](https://github.com/HEP-FCC/EventProducer) framework.

**Comment by tmadlener** [comment]
I am not sure whether the updated setup script fixed it or whether it is something else in your case @bistapf, but I cannot reproduce this at the moment.

- `test.sh`:
```bash
#!/usr/bin/env bash

source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
```

- `submit.cfg`:
```
executable = /afs/cern.ch/user/t/thmadlen/work/condor_debug/test.sh
log = /afs/cern.ch/user/t/thmadlen/work/condor_debug/condor_job.$(ClusterId).$(ProcId).log
output = /afs/cern.ch/user/t/thmadlen/work/condor_debug/condor_job.$(ClusterId).$(ProcId).out
error = /afs/cern.ch/user/t/thmadlen/work/condor_debug/condor_job.$(ClusterId).$(ProcId).err
requirements    = ( (OpSysAndVer =?= "CentOS7") && (Machine =!= LastRemoteHost) && (TARGET.has_avx2 =?= True) )

request_cpus = 1
request_memory = 1024
request_disk = 100

queue
```

**Comment by bistapf** [comment]
Thanks for your responses!

Strangely enough on Friday the issue was only partially fixed for me, as in some test jobs failed with this error while others worked fine. I could not figure out if there were any clear differences between those cases. 

The good news is though that by now it seems to have resolved itself - so far I have had ~1000 working jobs today. So I think we can consider this issue resolved (for now), even though I don't really understand where it even came from.

**Comment by bistapf** [comment]
> Try again, a new `setup.sh` is already on `cvmfs` Independently of whether it works or not (I'm guessing since I can't reproduce) can you post the output of the following script that you would need to submit (and if possible the same node if it's not reproducible all the time):
> 
> ```
> bash --version
> for f in /etc/*release; do
>   echo $f
>   cat $f
> done
> echo "cat /etc/*release | grep -E '^ID='"
> cat /etc/*release | grep -E '^ID='
> echo "cat /etc/*release | grep -E 'VERSION_ID'"
> cat /etc/*release | grep -E 'VERSION_ID'
> ```

Would the output of this script still be helpful?

**Comment by jmcarcell** [comment]
> > Try again, a new `setup.sh` is already on `cvmfs` Independently of whether it works or not (I'm guessing since I can't reproduce) can you post the output of the following script that you would need to submit (and if possible the same node if it's not reproducible all the time):
> > ```
> > bash --version
> > for f in /etc/*release; do
> >   echo $f
> >   cat $f
> > done
> > echo "cat /etc/*release | grep -E '^ID='"
> > cat /etc/*release | grep -E '^ID='
> > echo "cat /etc/*release | grep -E 'VERSION_ID'"
> > cat /etc/*release | grep -E 'VERSION_ID'
> > ```
> 
> Would the output of this script still be helpful?

Yes! And if you can do it in one of the nodes were it failed even better. The script was just grepping `/etc/*release` so I'd like to know what happened

I don't know why some jobs didn't work on Friday, maybe they weren't using the updated script yet? :shrug:
