### ISSUE TITLE
Upstreaming pandora packages?

### ISSUE THREAD

**Issue by wdconinc** [key4hep/key4hep-spack#485]
Would it be ok to upstream the pandora packages from here?

**Comment by vvolkl** [comment]
Yes. I haven't done so because of the cmake patches - I think they could be avoided. But no objections from me.

**Comment by jmcarcell** [comment]
Fine for me too
Progress here: https://github.com/spack/spack/pull/37714

**Comment by wdconinc** [comment]
Upstreamed.
