### ISSUE TITLE
Problems in opening files with emacs after sourcing nightlies

### ISSUE THREAD

**Issue by SwathiSasikumar** [key4hep/key4hep-spack#486]
I have found that there is a problem opening a file with emacs after sourcing the libraries with ```/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh```. The error message shows a random number and then ```emacs: symbol lookup error: /lib64/libpangocairo-1.0.so.0: undefined symbol: cairo_ft_font_options_substitute```.  I also find that this problem is consistent with some other editors e.g. ```geany```. This is however not a problem if the libraries are sourced with ```/cvmfs/sw.hsf.org/key4hep/setup.sh```. I use ```Alma9``` as my OS.

**Comment by Zehvogel** [comment]
Also happens for me when trying to use vscode...
```
[lreichen@pcphsft121 resolutions]$ . /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh setup-nightlies.sh
AlmaLinux 9 detected
Setting up the latest Key4HEP software stack from CVMFS ...
 ...  Key4HEP release: 2023-05-15
 ...  Use the following command to reproduce the current environment: 
 ... 
         source /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-15/x86_64-almalinux9-gcc11.3.1-opt/key4hep-stack/2023-05-15-z34lzz/setup.sh
 ... 
 ...  If you have any issues, comments or requests open an issue at https://github.com/key4hep/key4hep-spack/issues
[lreichen@pcphsft121 resolutions]$ code .
/usr/share/code/bin/../code: symbol lookup error: /lib64/libpangocairo-1.0.so.0: undefined symbol: cairo_ft_font_options_substitute
```

seems like this is not the first time this happens? https://github.com/HEP-FCC/fcc-spi/issues/21

Also, are the nightlies broken again? There is a 2023-05-16 release but it is not linked as latest and looks like it contains a broken symlink? @jmcarcell?

**Comment by Zehvogel** [comment]
https://github.com/key4hep/key4hep-spack/issues/52

**Comment by jmcarcell** [comment]
For emacs, the workaround is 
```
unset XDG_DATA_DIRS
LD_LIBRARY_PATH= emacs
```
Yes `2023-05-16` is a mistake and should have never been published. The latest is `2023-05-15` since now the head of podio and DD4hep 1.23 are not compatible anymore so the version of podio has to be pinned in the build... but I'm also trying to get other fixes in in the next nightly (prob Monday)

**Comment by andresailer** [comment]
The library that is loaded comes from the system folder (`/lib64`), so changing the cairo build in Key4hep shouldn't make any difference. Maybe adding `pango` to the stack would make emacs work.

**Comment by Zehvogel** [comment]
The system lib picks up `libcairo` as it is in the `LD_LIBRARY_PATH`.

```
[lreichen@pcphsft121 resolutions]$ . /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh setup-nightlies.sh
[...]
[lreichen@pcphsft121 resolutions]$ ldd /usr/lib64/libpangocairo-1.0.so.0.4800.7
[...]
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007ffb8d1b4000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007ffb8d19a000)
[...]
	libgobject-2.0.so.0 => /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-04/x86_64-almalinux9-gcc11.3.1-opt/glib/2.76.1-fbiy3h/lib/libgobject-2.0.so.0 (0x00007ffb8cf02000)
	libfontconfig.so.1 => /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-04/x86_64-almalinux9-gcc11.3.1-opt/fontconfig/2.14.2-vv3nmk/lib/libfontconfig.so.1 (0x00007ffb8ceb6000)
	libcairo.so.2 => /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-04/x86_64-almalinux9-gcc11.3.1-opt/cairo/1.16.0-ado6wx/lib/libcairo.so.2 (0x00007ffb8cdc2000)
[...]
```
Without sourcing
```
[lreichen@pcphsft121 resolutions]$ ldd /usr/lib64/libpangocairo-1.0.so.0.4800.7
[...]
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f1c26a09000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f1c269ef000)
[...]
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f1c26614000)
[...]
```
But adding `pango` to the stack should also work, yes.

**Comment by andresailer** [comment]
Indeed, you are correct!

**Comment by jmcarcell** [comment]
By dropping `LD_LIBRARY_PATH`, this has been fixed on Centos7 on the nightlies. On alma9 one does not need to unset `LD_LIBRARY_PATH` anymore so the workaround is just to `unset XDG_DATA_DIRS`. @Zehvogel also reported that on alma9 vscode works fine without any workarounds

**Comment by jmcarcell** [comment]
This has been now fixed in the nightlies by unsetting `XDG_DATA_DIRS`, hopefully there are no side effects since there were only two (non-key4hep) packages in that path
