### ISSUE TITLE
Missing LCIO output from ddsim

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/key4hep-spack#487]
ddsim is missing all the calorimeter hit collections in the output in dd4hep versions [v01.21, v01-23].

See: https://github.com/AIDASoft/DD4hep/pull/1019

If we are not switching to v01-24 by tomorrow the above patch should probably be added to the build?

**Comment by jmcarcell** [comment]
This has been patched for the nightlies. Note that the latest release has DD4hep 1.23 **without** the patch, so if you need the patch you should source the nightlies until there is a new release
