### ISSUE TITLE
[Enhancement] Compiling MarlinUtil w/o explicit GSL flag

### ISSUE THREAD

**Issue by dudarboh** [key4hep/key4hep-spack#489]
## Issue

Compiling MarlinUtil requires explicit `-DGSL_DIR` flag, despite GSL path is already being present inside `CMAKE_PREFIX_PATH`.

```bash
source /cvmfs/ilc.desy.de/key4hep/spackages/key4hep-stack/2023-03-15/x86_64-centos7-gcc11.2.0-opt/p24fynst3gd5t37uh7n3465q5wjrty6v/setup.sh

echo $CMAKE_PREFIX_PATH | sed 's/:/:\n/g' |grep "/gsl"
/cvmfs/ilc.desy.de/key4hep/spackages/gsl/2.7/x86_64-centos7-gcc11.2.0-opt/qhbgix76rutqco724q2bfhfmje3mgek2:

cd /path/to/MarlinUtil
mkdir build && cd build
cmake .. -DGSL_DIR=/cvmfs/ilc.desy.de/key4hep/spackages/gsl/2.7/x86_64-centos7-gcc11.2.0-opt/qhbgix76rutqco724q2bfhfmje3mgek2
```

Without this flag, system GSL is being found, which is not what we want.

## Enhancement

It would be nice to be able to compile the MarlinUtil out of the box with a simple

```bash
cmake ..
```

**Comment by jmcarcell** [comment]
Do you have `GSL` installed in the system folders? Like `/usr/bin` /usr/lib` and so on?

On lxplus with the current nightlies or the latest release it works fine without any flags
```
-- Check for GSL (2.7.1)
-- Check for GSL_LIBRARIES: gsl;gslcblas
-- Check for GSL_GSL_LIBRARY: /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-20/x86_64-centos7-gcc12.2.0-opt/gsl/2.7.1-dbi62x/lib/libgsl.so -- ok
-- Check for GSL_GSLCBLAS_LIBRARY: /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-20/x86_64-centos7-gcc12.2.0-opt/gsl/2.7.1-dbi62x/lib/libgslcblas.so -- ok
```
but that's because GSL is not installed locally

**Comment by dudarboh** [comment]
Yep, on the DESY NAF servers GSL is installed in `/usr/lib64/`, so cmake picks up it...
```
-- Check for GSL (1.15)
-- Check for GSL_LIBRARIES: gsl;gslcblas
-- Check for GSL_GSL_LIBRARY: /usr/lib64/libgsl.so -- ok
-- Check for GSL_GSLCBLAS_LIBRARY: /usr/lib64/libgslcblas.so -- ok
```

I was iterating on this with @tmadlener in private conversation, he mentioned that in the current builds it is also picked up directly:
https://github.com/key4hep/key4hep-spack/blob/73fe2092ae41f2ac96833b302b3e8c72a68691f0/packages/marlinutil/package.py#L40-L42

**Comment by tmadlener** [comment]
In principle setting `GSL_ROOT_DIR` should be enough for `FindGSL.cmake` to pick it up, IIUC: https://cmake.org/cmake/help/latest/module/FindGSL.html#hints

**Comment by jmcarcell** [comment]
It's now on the stack, see https://github.com/key4hep/key4hep-spack/commit/3f374fb3763ae57e1403b91b835e2cfd988174fa
As a fix for the release @dudarboh is using this could be added to `/cvmfs/ilc.desy.de/key4hep/spackages/key4hep-stack/2023-03-15/x86_64-centos7-gcc11.2.0-opt/p24fynst3gd5t37uh7n3465q5wjrty6v/setup.sh`
```
export GSL_ROOT_DIR=/cvmfs/ilc.desy.de/key4hep/spackages/gsl/2.7/x86_64-centos7-gcc11.2.0-opt/qhbgix76rutqco724q2bfhfmje3mgek2
```
since this is not going to fix already existing releases

**Comment by jmcarcell** [comment]
This was added to spack: https://github.com/spack/spack/pull/38464, so there is nothing else to do here.
