### ISSUE TITLE
Dump out version for k4-spack and builtin

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#49]
Since the versions of k4-spack and builtin are constantly changing it may be difficult to track versions and create reproduciable builds.  spack does a good job of tracking the versions of individual packages, but there is no current mechanism for recording what build was used.

One thing that could be done is to modify the package.py for key4hep-stack to dump out the commit id of the builtin and k4-spack versions so that this can be recorded.  Also we can put some diagnostic tools in the key4hep-stack package to for example dump out the system characteristics of a build.

Thoughts?

**Comment by vvolkl** [comment]
Hi @joequant,

that's a very good point! The simplest solution (once things get a bit more stable) is simply to version k4-spack and then to cite both it's version and the version of spack used. I'm not sure if there is any special tooling needed for that, but maybe you can open an issue or ask on the spack slack? This will most likely be of interest not only to us.

**Comment by jmcarcell** [comment]
This is now done in the latest Alma9 nighty by adding a `.spack-commit` and a `.key4hep-spack-commit` file containing the respective commits, otherwise the builds are hard to reproduce exactly. This will be the default from now on. Closing...

**Comment by tmadlener** [comment]
Just for clarification (and documentation). Where are these files place in the end?
