### ISSUE TITLE
Error installing Whizard

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/key4hep-spack#491]
I was trying to setup a local key4hep installation in an environment based on the nightlies with [this `spack.yaml`](https://github.com/key4hep/key4hep-spack/files/11674561/spack.yaml.txt) ( I just added a .txt to be able to attach it to the issue...)
 - OS version: almalinux9
 - Compiler version: gcc11.3.1

All packages but Whizard (and ilcsoft, key4hep-stack which depend on it) install successfully.

The Whizard installation fails after a while with
```
sh: line 1: /spack/lib/spack/env/gcc/gcc: No such file or directory
File "caml_startup", line 1:
Error: I/O error: /spack/lib/spack/env/gcc/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -Wall -Wdeclaration-after-statement -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections  -Wl,-E  -o 'circe2_tool.opt'  '-L/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/ocaml/4.13.1-rnarqd/lib/ocaml'  '/tmp/lreichen/camlstartupa024ca.o' '/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/ocaml/4.13.1-rnarqd/lib/ocaml/std_exit.o' 'circe2_tool.o' 'histogram.o' 'commands.o' 'events.o' 'parser.o' 'events_lexer.o' 'lexer.o' 'syntax.o' 'grid.o' 'division.o' 'filter.o' 'diffmaps.o' 'diffmap.o' 'float.o' 'thoMatrix.o' 'thoArray.o' 'OUnitDiff.o' 'OUnit.o' 'bigarray_compat.o' '/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/ocaml/4.13.1-rnarqd/lib/ocaml/unix.a' '/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/ocaml/4.13.1-rnarqd/lib/ocaml/stdlib.a' '-lunix' '/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/ocaml/4.13.1-rnarqd/lib/ocaml/libasmrun.a' -lm 
make[2]: *** [Makefile:1294: circe2_tool.opt] Error 2
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  /usr/bin/gfortran -g -O2 -c circe2.f90 -o circe2.o >/dev/null 2>&1
make[2]: Leaving directory '/tmp/lreichen/spack-stage/spack-stage-whizard-3.1.0-apytnihwt266b4bthuf3hwaqaoyfrhuv/spack-src/circe2/src'
make[1]: *** [Makefile:658: all-recursive] Error 1
make[1]: Leaving directory '/tmp/lreichen/spack-stage/spack-stage-whizard-3.1.0-apytnihwt266b4bthuf3hwaqaoyfrhuv/spack-src/circe2'
make: *** [Makefile:787: all-recursive] Error 1
```
Here is the full output and the output of the concretizer:
[spack-build-out.txt](https://github.com/key4hep/key4hep-spack/files/11674633/spack-build-out.txt)
[concretize_wbug.txt](https://github.com/key4hep/key4hep-spack/files/11674551/concretize_wbug.txt)

Looking at the build output I also noticed that building with lcio and hepmc seems to be broken??
There is this warning
```
configure: WARNING: unrecognized options: --with-lcio, --with-hepmc
```
and indeed, later on the Whizard output says:
```
--------------------------------------------------------------
---      External packages      ---
--------------------------------------------------------------
HepMC (event format):   no
HDF5 (binary format):   no
LCIO (event format) :   no
LHAPDF (PDF sets)   :   no
HOPPET (PDF match.) :   no
FastJet (clustering):   no
PYTHIA8 (QCD)       :   yes, v8.309      
GoSam (OLP)         :   no
OpenLoops (OLP)     :   yes, vbeta
           path     :   /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/openloops/2.1.2-nnlldb
RECOLA (OLP)        :   no
LoopTools           :   no
--------------------------------------------------------------
```
and doing `./configure --help` in the build directory does not list `--with-lcio` as an option however `--with-hepmc` is listed... :shrug:

**Comment by tmadlener** [comment]
The configure warnings are unrelated, I think. I have seen them before in succesfull whizard builds as well.  The lines

```
sh: line 1: /spack/lib/spack/env/gcc/gcc: No such file or directory
File "caml_startup", line 1:
Error: I/O error: /spack/lib/spack/env/gcc/gcc -O2 -fno-strict-aliasing [...]
```

make me suspect that you are running out of disk space somewhere, could be the spack-stage, could be a too small cvmfs cache, could be other things, but I think it is unrelated to spack or whizard in this case.

**Comment by Zehvogel** [comment]
I should have more than enough free disk space and inodes.

**Comment by tmadlener** [comment]
Does `/spack/lib/spack/env/gcc/gcc` exist and is readable? (Potentially needs to be checked inside the build environment)

**Comment by Zehvogel** [comment]
No `/spack/lib/spack/env/gcc/gcc` does not exist, also not in the build environment.
I was wondering if that is the issue and where that is supposed to come from but marked it down as probably some spack magic...
However, this path does exist on the machine the nightlies are build on and I take ocaml from the nightlies.
So ocaml seems to remember which compiler was used to build it and tries to use the same one?
```
[key4hep-nightly-upstream-wbug] [lreichen@pcphsft121 test8]$ strings /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/ocaml/4.13.1-rnarqd/bin/ocamlopt.opt | grep spack
/spack/lib/spack/env/gcc/gcc
/spack/lib/spack/env/gcc/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -Wall -Wdeclaration-after-statement -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections  -Wl,-E 
/spack/lib/spack/env/gcc/gcc -shared 
/tmp/root/spack-stage/spack-stage-ocaml-4.13.1-rnarqdefykepc3shbdl3slfk3tbo7znk/spack-src/stdlib
/tmp/root/spack-stage/spack-stage-ocaml-4.13.1-rnarqdefykepc3shbdl3slfk3tbo7znk/spack-src
/tmp/root/spack-stage/spack-stage-ocaml-4.13.1-rnarqdefykepc3shbdl3slfk3tbo7znk/spack-src/runtime
```

**Comment by jmcarcell** [comment]
This is something that works in the nightlies when one of the full builds is used from scratch. For example, the build for `2023-06-05` has `whizard` built:
``` shell
/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-05/x86_64-almalinux9-gcc11.3.1-opt/whizard
```

and uses `ocaml` from the build on `2023-05-30`. I'll try with your exact setup

**Comment by Zehvogel** [comment]
Looks like this is the case, weird that it only happens when ocamlopt is used for linking while compilation works... but after all a ocaml/spack issue :/ 
```
[lreichen@pcphsft121 test8]$ ocamlopt.opt -config
version: 4.13.1
standard_library_default: /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/ocaml/4.13.1-rnarqd/lib/ocaml
standard_library: /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-30/x86_64-almalinux9-gcc11.3.1-opt/ocaml/4.13.1-rnarqd/lib/ocaml
ccomp_type: cc
c_compiler: /spack/lib/spack/env/gcc/gcc
ocamlc_cflags: -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC 
ocamlc_cppflags: -D_FILE_OFFSET_BITS=64 
ocamlopt_cflags: -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC 
ocamlopt_cppflags: -D_FILE_OFFSET_BITS=64 
bytecomp_c_compiler: /spack/lib/spack/env/gcc/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC  -D_FILE_OFFSET_BITS=64 
native_c_compiler: /spack/lib/spack/env/gcc/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC  -D_FILE_OFFSET_BITS=64 
bytecomp_c_libraries: -lm  -lpthread
native_c_libraries: -lm 
native_pack_linker: ld -r -o 
...
```

**Comment by jmcarcell** [comment]
As per my comment above the workaround is to clone spack to / and run from there while this is fixed. Alternatively if you make a symlink of `/spack/lib/spack/env/gcc/gcc` to `gcc` it may work

**Comment by Zehvogel** [comment]
I have now symlinked my local spack folder to `/spack` which is ugly but lets me keep working, thx :)

**Comment by jmcarcell** [comment]
Fixed by https://github.com/spack/spack/pull/38251, will be fixed in the next nightly
