### ISSUE TITLE
Nightly builds are not usable with Marlin

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#492]
The new setup for the install prefixes for the nightly builds puts equal signs (specifically `=develop`) into the paths. This breaks workflows that use Marlin using paths as input variables, the most important one being `$lcgeo_DIR`, e.g.

```bash
Marlin --constant.lcgeo_DIR=$lcgeo_DIR [...]
```
Marlin uses the `=` as delimiter between the argument key and its value for parsing and cannot deal with additional `=` signs in the value.

**Comment by andresailer** [comment]
Does it work if you quote the arguments?

**Comment by tmadlener** [comment]
No, unfortunately that doesn't fix things. Neither `"$lcgeo_DIR"` nor quoting the expanded variable changes things. The quickest and lowest effort workaround for the moment is probably to create a local symlink and then use that.

```bash
ln -s $lcgeo_DIR lcgeo_DIR
Marlin --constant.lcgeo_DIR=./lcgeo_DIR [...]
```

**Comment by Zehvogel** [comment]
Do we still have no better solution for this?

**Comment by tmadlener** [comment]
This has changed in upstream spack to use a `_` instead of a `=`. Hence, everything works again in nightly builds.
