### ISSUE TITLE
Detector builders from FCCDetectors not linked properly in the nightlies

### ISSUE THREAD

**Issue by BrieucF** [key4hep/key4hep-spack#499]
Sourcing the nightlies on lxplus and trying to run ddsim on a compact file from FCCDetectors with e.g. 
```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
ddsim --compactFile $FCCDETECTORS/Detector/DetFCCeeCLD/compact/FCCee_o2_v02/FCCee_o2_v02.xml --enableGun --gun.distribution uniform --gun.energy "10*GeV" --gun.particle mu- --numberOfEvents 100 --outputFile Step1.root
``` 

crashes with 

`No factory with name Create(CLD_GenericCalBarrel_o1_v01) for type CLD_GenericCalBarrel_o1_v01 found.` 

Running `LD_LIBRARY_PATH=$FCCDETECTORS/../../lib/:$FCCDETECTORS/../../lib64/:$LD_LIBRARY_PATH` cures it.

**Comment by jmcarcell** [comment]
This has been fixed in the nightlies by adding the path to `LD_LIBRARY_PATH`
