### ISSUE TITLE
environment modules now required for setup

### ISSUE THREAD

**Issue by vvolkl** [key4hep/key4hep-spack#50]
The setup script for the spack build uses the `module load` command, which is available on lxplus, but not on every centos7 installation, unfortunately also not on the clicdp/cc7-lcg docker image used in the CI.

**Comment by andresailer** [comment]
We should probably create a repo here, and build the docker images for cc7/8 based on the sft images.

**Comment by vvolkl** [comment]
`module load` is no longer used in the setup script.
