### ISSUE TITLE
Add `conddbmysql` to ilcsoft package

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#517]
The `conddbmysql` package has a recipe but is not included as a dependency in `ilcsoft`. I suppose this has historical reasons, maybe @vvolkl still remembers why this is not there by default?

It looks like it would be possilbe to easily toggle this by requiring `lccd +conddbmysql`, but that is off by default:
https://github.com/key4hep/key4hep-spack/blob/2914c611ec13f90bf635e2fd7caa41ede1a0c332/packages/lccd/package.py#L28-L32

**Comment by jmcarcell** [comment]
Is it needed, is anybody going to use this? I guess it has been off forever

**Comment by tmadlener** [comment]
I was stumbling over this when trying to run the LCCD CI on the key4hep stack. It is built with the iLCSoft stack via iLCInstall, but I will have to investigate on the uses.

In any case, I think we could build it (or try to), just to have a sort of trigger when things start to break.

**Comment by jmcarcell** [comment]
Now it is being built with the nightlies, with today's nightly having it (changes in https://github.com/key4hep/key4hep-spack/commit/5a1f8c39736c1389be1718616c0d3888c0b8a39f)

**Comment by tmadlener** [comment]
Thanks :)
