### ISSUE TITLE
Add HEED_DATABASE environment variable

### ISSUE THREAD

**Issue by wenxingfang** [key4hep/key4hep-spack#518]
Dear Author,

I am using Garfield++ for the simulation in the CEPCSW. In the CEPCSW, we have set the environment variable HEED_DATABASE (which is needed, as explained in [here](https://garfieldpp.web.cern.ch/garfieldpp/getting-started/) )like this 
```
    export GARFIELD_HOME=$CEPCSWEXTERNAL/Garfield++
    export GARFIELD=${GARFIELD_HOME}
    export HEED_DATABASE=$GARFIELD_HOME/share/Heed/database/
```

When using key4hep-spack, as the HEED_DATABASE is unset, it gives an error when doing compiling 
```
[ 94%] Linking CXX shared module libDetSimDedx.so
Heed:
    Could not retrieve database path.
ExAtomPhotoAbsCS::ExAtomPhotoAbsCS(...) const: ERROR:
cannot open file /shelllist.dat
FunNameStack: s_init=1 qname=1
  0  ExAtomPhotoAbsCS::ExAtomPhotoAbsCS(...) const
File is /tmp/root/spack-stage/spack-stage-garfieldpp-4.0-rsovv5qvcd47d7q74wzw6zt45y7fmg62/spack-src/Heed/heed++/code/PhotoAbsCS.cpp , line number is 1042
spexit_action: the streams will be now flushed
spexit_action: the abort function is called
/bin/sh: line 1: 21130 Aborted                 (core dumped) ../../run /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-24/x86_64-centos7-gcc12.2.0-opt/gaudi/36.10-xtb3ml/bin/listcomponents --output DetSimDedx.components libDetSimDedx.so
gmake[2]: *** [Simulation/DetSimDedx/CMakeFiles/DetSimDedx.dir/build.make:263: Simulation/DetSimDedx/libDetSimDedx.so] Error 134
gmake[2]: *** Deleting file 'Simulation/DetSimDedx/libDetSimDedx.so'
gmake[1]: *** [CMakeFiles/Makefile2:3112: Simulation/DetSimDedx/CMakeFiles/DetSimDedx.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```
Do you have any suggestions to solve the problem?

Best,
Wenxing

**Comment by tmadlener** [comment]
Hi @wenxingfang, do I understand correctly that the error you see is when you build another package against Garfield? In this case, I suppose it is `cepcsw`?

The easiest way to solve this is to make spack setup the corresponding environment variable in the [`garfieldpp` package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/garfieldpp/package.py) by defining them in the `setup_run_environment` (or if it is necessary for dependent builds only in the `setup_dependent_build_environment`) function. [Here](https://spack.readthedocs.io/en/latest/spack.html#spack.package_base.PackageBase.setup_run_environment) is the documentation in spack. And [here](https://github.com/spack/spack/blob/0e27f0561182e21c838606074ff3eeba0543d6ce/var/spack/repos/builtin/packages/podio/package.py#L143-L153) is an example of how we do it in podio.

**Comment by mirguest** [comment]
> The easiest way to solve this is to make spack setup the corresponding environment variable in the [`garfieldpp` package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/garfieldpp/package.py) by defining them in the `setup_run_environment` (or if it is necessary for dependent builds only in the `setup_dependent_build_environment`) function. [Here](https://spack.readthedocs.io/en/latest/spack.html#spack.package_base.PackageBase.setup_run_environment) is the documentation in spack. And [here](https://github.com/spack/spack/blob/0e27f0561182e21c838606074ff3eeba0543d6ce/var/spack/repos/builtin/packages/podio/package.py#L143-L153) is an example of how we do it in podio.

Thanks @tmadlener. I will try to setup this environment variable in the garfieldpp package. 

Tao

**Comment by jmcarcell** [comment]
If you do it and give me where the change is I can cherry pick it for the nightlies and you'll have it before it's merged in spack (and we pick up the right spack version)

**Comment by wenxingfang** [comment]
@jmcarcell Can you help to update the key4hep-spack to have the changes included?

**Comment by wenxingfang** [comment]
Hi @jmcarcell, do you have any comments?

**Comment by jmcarcell** [comment]
Sorry for the delay. The nightlies now have that variable and I made a pull request in spack: https://github.com/spack/spack/pull/40504
Let me know if everything is fine

**Comment by wenxingfang** [comment]
@jmcarcell It works now, thanks a lot!
