### ISSUE TITLE
Whizard does not have LCIO in nightly builds 

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#533]
The `variants` do not seem to be respected from here:
https://github.com/key4hep/key4hep-spack/blob/bb97fa8dbfb82696e69961a5b18893764cb2145e/environments/key4hep-common/packages.yaml#L63-L64

Maybe this should also be flipped to `require`.

**Comment by tmadlener** [comment]
Actually, checking the configure log again:
```
LCIO (event format) :   no
```

**Comment by jmcarcell** [comment]
This should be fixed by https://github.com/spack/spack/pull/40316, that is already being picked up for the nightlies
