### ISSUE TITLE
New Key4hep release

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#536]
This issue is here to keep track of the PRs that should still be merged for a new Key4hep release as well as all of the tags that were made (and still need to be made)?

Please add PRs and tags that still need to be made to the list below.

## PRs

- [x] https://github.com/key4hep/EDM4hep/pull/227
- [x] https://github.com/key4hep/k4SimDelphes/pull/112
- [x] https://github.com/iLCSoft/LCIO/pull/177
- [x] https://github.com/spack/spack/pull/41103 (podio tag)
- [x] https://github.com/spack/spack/pull/41102 (lcio tag)

## Tags

- [x] podio v00-17-03
- [x] EDM4hep v00-10-02
- [x] k4FWCore v01-00pre17
- [x] k4MarlinWrapper v00-07
- [x] k4EDM4hep2LcioConv v00-07
- [x] CEPCSW 0.2.7
- [x] FCALClusterer 1.0.6
- [x] DD4hep 1.27
- [x] MarlinUtil v01-17-02
- [x] FCCAnalyses v0.8.0
- [x] FCCSW v1.0pre08
- [x] ~k4Gen~ (no changes since last tag)
- [ ] k4geo
- [x] FCCDetectors v0.1pre10
- [x] k4SimDelphes v00-06
- [x] k4-project-template v0.4.0
- [x] k4RecCalorimter v0.1.0pre12
- [x] k4SimGeant4 v0.1.0pre13
- [x] ConformalTracking v01-12
- [x] LCIO v02-20-01

**Comment by jmcarcell** [comment]
I just saw you edited it @kjvbrt but I was going to ask for a timeline for the PRs, maybe next week we can start thinking about tagging?

**Comment by kjvbrt** [comment]
Hi @jmcarcell. We plan to do all the tags tomorrow/Thursday.

**Comment by Zehvogel** [comment]
@tmadlener can you also make a new MarlinUtil tag?

**Comment by jmcarcell** [comment]
We should check this automatically, i.e. any packages that have commits after the tag that was used for the last release probably should be tagged. I'll have a look at this so we don't forget any

**Comment by tmadlener** [comment]
I put all the open tags into the top level comment together with two currently open PRs that should still be included.

k4SimDelphes can in principle be used in its current version since there was only one PR that fixed some cmake warnings since then. Since k4SimDelphes is effectively a "leaf" in the dependency tree, this should be fairly straight forward to pick up in a small follow up release if necessary (i.e. if the PR takes too long).

For the following packages I am not entirely sure which PRs still need to go in:
- k4FWCore
- k4MarlinWrapper
- k4geo

@kjvbrt can you make tags for the `FCC[...]` repositories once they are ready (or delegate to someone to make the tags) and tick the boxes in the top level comment? (If I just missed them, could you put the versions in?)

@jmcarcell I think you have the best overview over k4FWCore and know which PRs should still be in the tag and which ones we can leave open. Can you put the ones that need to go in, into the top level comment?

@andresailer I suppose you know best about k4geo, so could you do the same for that?

**Comment by andresailer** [comment]
We have this issue with the MarlinWrapper https://github.com/key4hep/k4MarlinWrapper/issues/158 that would cause occasional crashes, so would be nice to fix this before.

**Comment by andresailer** [comment]
New ConformalTracking tag https://github.com/iLCSoft/ConformalTracking/releases/tag/v01-12
