### ISSUE TITLE
Pythia8 environment variables are not set for CentOS7 and Alma9

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#540]
The `PYTHIA8` and `PYTHIA8DATA` environment variables are not set in the current nightly builds, making the CI for k4SimDelphes fail: https://github.com/key4hep/k4SimDelphes/actions/runs/6731118066/job/18295169237?pr=112#step:5:38

In principle these variables are set in the spack recipe [here](https://github.com/spack/spack/blob/80944d22f775b014cfd201e895fc8777a2038786/var/spack/repos/builtin/packages/pythia8/package.py#L168-L176), so I am not sure what is happening in the nightly builds that prevents setting these correctly.

- For CentOS7, I checked
```
/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-11-02/x86_64-centos7-gcc12.2.0-opt/key4hep-stack/2023-11-02-oemzwb/setup.sh
```
- For Alma9, I checked
```
/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-11-02/x86_64-almalinux9-gcc11.3.1-opt/key4hep-stack/2023-11-02-pppkxq/setup.sh
```
- For Ubuntu 22, I get a much older nightly build and things are still working
```
/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-10-20/x86_64-ubuntu22.04-gcc11.3.0-opt/key4hep-stack/2023-10-19-eh7r2x/setup.sh
```

**Comment by vvolkl** [comment]
The upstream spack recipe only does `setup_dependent_run_environment`, which seems like a bug. You need those env vars to run pythia8 itself, so it should also do `setup_run_environment`

**Comment by tmadlener** [comment]
I was also thinking that, but that change has been introduced ~2 years ago and it has been working for quite some time, so I am not sure why it stopped working now or why it works for Ubuntu but not the rest.

**Comment by tmadlener** [comment]
My suspicion is this commit here: https://github.com/spack/spack/commit/72b36ac14446782f47519db8ee5cff6631b2b4c9

**Comment by tmadlener** [comment]
That might not be it in the end. In my local development environment I created with spack, `PYTHIA8` is set correctly. This is also on Ubuntu, so I am not sure whether this is an OS issue?

**Comment by jmcarcell** [comment]
This isn't happening as of today. That commit lead to some problems related to how `setup_dependent_run_environment` works but I think they fixed it after I complained.
