### ISSUE TITLE
Cannot run within the fccanalysis framework using 2023-11-27 release 

### ISSUE THREAD

**Issue by pianonick411** [key4hep/key4hep-spack#545]
- OS version: centos7
 - Compiler version: GCC 12.2.0
 - Package version: Key4HEP release: 2023-11-27
 - Reproduced by: 
 - 1. cd /eos/user/n/nipinto/FCCAnalyses
 - 2. Run the setup script: "source setup.sh"
 - 3. run any fccsw tool ( e.g. "fccanalysis run analysis.py" or "fccanalysis plots plots.py" ) 
 - Output: 
[FCCSWerr.log](https://github.com/key4hep/key4hep-spack/files/13479381/FCCSWerr.log)

 - Goal: I'm trying to run an analysis script within the FCCSW framework. This script was working as of 2023-11-25, but has stopped working as of today. The error seems to suggest that multiple versions of ROOT are loaded simultaneously. I'm not sure how to rectify this issue.

**Comment by kjvbrt** [comment]
Hi @pianonick411, as @tmadlener said the stack you are running and which the FCCAnalyses was compiled with are probably different. Have you tried to recompile your local copy of FCCAnalyses?
Can you try to do this:
```
cd /eos/user/n/nipinto/FCCAnalyses
source setup.sh
fccanalysis build -c
```

`fccanalysis build -c` is a shortcut for the full compilation instructions done using cmake.

**Comment by pianonick411** [comment]
Hi @kjvbrt, this solved the issue. Thank you!
