### ISSUE TITLE
`jupytext` no longer available on Centos7 and and Alma9

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#547]
We see a failure in the k4MarlinWrapper CI:

https://github.com/key4hep/k4MarlinWrapper/actions/runs/7048032203/job/19183244571#step:6:22

Not sure if anything related to this has changed.

edit: Things seem to be working on the Ubuntu "nightlies", but I am picking up a rather old one there:
```
 ...  Key4HEP release: 2023-10-19
 ...  Use the following command to reproduce the current environment: 
 ... 
         source /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-10-20/x86_64-ubuntu22.04-gcc11.3.0-opt/key4hep-stack/2023-10-19-eh7r2x/setup.sh
 ... 
 ...  If you have any issues, comments or requests, open an issue at https://github.com/key4hep/key4hep-spack/issues
```

**Comment by jmcarcell** [comment]
This is no longer true
