### ISSUE TITLE
Whizard is not linked with HepMC

### ISSUE THREAD

**Issue by dirkzerwas** [key4hep/key4hep-spack#549]
Hello,

We are trying to set up some standard MC workflows for the ECFA study and ran into a problem:

setup:
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
running an input of 2 fermion production with the option
sample_format = hepmc
results in:
| Simulation: requested number of events = 100
|             corr. to luminosity [fb-1] =   2.4280E-05
| Events: writing to HepMC file 'proc.hepmc'
************************************************************
*** HepMC: Error: library not linked, WHIZARD terminates ***
************************************************************

when the sample_format option is removed the generation runs and produces an evx output (as expected)
when the sample_format option is set to lcio the generation runs and produces an lcio output (as expected)
so the error is  really related to the choice of the format.

In the ilcsoft package.py we found:
 depends_on("whizard +lcio +openloops hepmc=2")
so I would have expected to have at least HepMCv2 available?

Could there be a problem with the build or am I doing something wrong?

Best,
Dirk

**Comment by tmadlener** [comment]
Checking the build logs it looks like we are indeed not building against HepMC because it cannot be found during `configure`:
```
[...]
312 configure: --------------------------------------------------------------
313 configure: --- HepMC ---
314 configure:
315 checking for HepMC3-config... no
316 checking for HepMC3 or newer... no
317 configure: HepMC3 not found, incompatible, or HepMC3-config not found
318 configure: looking for HepMC2 instead ...
319 checking the HepMC version... unknown
320 checking for HepMC... (disabled)
321 configure: ---------------------------
[...]
```

I will have a look to see why whizard doesn't pick up HepMC even though we in principle want to build it with HepMC.

**Comment by jmcarcell** [comment]
This should be now fixed in the nightlies, can you check @dirkzerwas that it works now?

**Comment by tmadlener** [comment]
I think we still need https://github.com/spack/spack/pull/41538 to be merged upstream before this will have the desired effect. Unless, you have cherry-picked that?

**Comment by jmcarcell** [comment]
Yeah that is cherry picked

**Comment by dirkzerwas** [comment]
Tested with setup:
Setting up the latest Key4HEP software stack from CVMFS . 
...  Key4HEP release: 2023-12-15
.output:
| Events: writing to HepMC file 'proc.hepmc'

Works, great, thanks!

Dirk
