### ISSUE TITLE
LCFIPlus broken in nightly builds and latest release with CentOS7

### ISSUE THREAD

**Issue by BrieucF** [key4hep/key4hep-spack#558]
The CLD reconstruction seems to be broken with CentOS 7 but works with the Alma9 flavor.

Reproducer: 

```
git clone https://github.com/key4hep/CLDConfig.git
cd CLDConfig/CLDConfig
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
ddsim --compactFile $K4GEO/FCCee/CLD/compact/CLD_o2_v05/CLD_o2_v05.xml \
      --enableGun \
      --gun.distribution uniform \
      --gun.energy "10*GeV" \
      --gun.particle mu- \
      --numberOfEvents 100 \
      --outputFile Step1_edm4hep.root
k4run CLDReconstruction.py --inputFiles Step1_edm4hep.root
```

Stack trace: [stack_trace_CLD_reco_COS7.txt](https://github.com/key4hep/key4hep-spack/files/14181435/stack_trace_CLD_reco_COS7.txt)

**Comment by tmadlener** [comment]
OK. Thanks for checking. I will have a look at the k4MarlinWrapper one, and I think that should also solve this, since in the end also CLD reco is using that.

**Comment by tmadlener** [comment]
Quick update on the little things I have figured out so far using CLIC reco (but I would assume CLD reco is the same / similar). Playing around with commenting out a few algorithms, I think I have narrowed it down to LCFIPlus being the offender here. That would also make sense, as that uses some ROOT things internally and the segmentation violation is inside ROOT. I haven't been able to debug it much further and I also don't know why it only happens on CentOS7 only yet.

**Comment by tmadlener** [comment]
It also seems to have been present for at least three weeks now, or at least I can find CI runs that show the issue from 3 weeks ago, e.g. https://github.com/key4hep/k4MarlinWrapper/actions/runs/7519772256/job/20473078519

**Comment by jmcarcell** [comment]
Let's check this again tomorrow and see if it's fixed. The workaround seems to be to build LCFIPlus locally

**Comment by jmcarcell** [comment]
Some hints by comparing to a working version, it doesn't work when:
- Building with C++20 instead of C++17
- Having ROOT 6.28.10 instead of ROOT 6.28.06

In case it's LCFIPlus by checking the dates, it's not due to https://github.com/iLCSoft/LCFIVertex/pull/9 and the other dependencies remain unchanged

**Comment by jmcarcell** [comment]
Since there aren't going to be any more releases nor nightlies with CentOS 7 and it's unlikely anyone will have a look and fix it I'm going to close this.
