### ISSUE TITLE
k4fwcore and podio: unable to concretize 

### ISSUE THREAD

**Issue by wdconinc** [key4hep/key4hep-spack#562]
Podio in spack develop is deprecated for all but 0.99. k4fwcore requires podio@:0.17.3 for all releases in key4hep-spack. This makes k4fwcore not installable.

Suggestion: don't be as aggressive with the podio deprecation in spack :-) (cc @tmadlener)

As a practical matter, do you use key4hep-spack 'versions' by commit hash to build key4hep environments? Do you just ignore deprecated in key4hep builds? Is there any workflow against spack develop that is should catch this?

**Comment by tmadlener** [comment]
> Suggestion: don't be as aggressive with the podio deprecation in spack :-) (cc @tmadlener)

Apologies. Didn't check too carefully here, apparently


Given that we regularly build k4FWCore against `podio@master`, we could probably just update that depedency.

**Comment by wdconinc** [comment]
> at least the latest tag of k4FWCore can be built against newer podio versions

Then I'll just file a PR against k4fwcore here to make them accessible.

**Comment by jmcarcell** [comment]
New versions added in https://github.com/key4hep/key4hep-spack/pull/563

> As a practical matter, do you use key4hep-spack 'versions' by commit hash to build key4hep environments? Do you just ignore deprecated in key4hep builds? Is there any workflow against spack develop that is should catch this?

For the nightlies the default branch is used like `edm4hep@main`. We don't have anything that would have caught this, only we would have seen this by trying to build a stable release with the latest tags

**Comment by wdconinc** [comment]
> For the nightlies the default branch is used like `edm4hep@main`. We don't have anything that would have caught this, only we would have seen this by trying to build a stable release with the latest tags

I'm still not sure what the recommendation is then if we want to use key4hep-spack. What version of spack are you promising compatibility with? We want to avoid having our pipelines or development workflows break at random time. Two options:
- only recommended way is using a fixed hash (since no recent versions on key4hep-spack),
- you aim for key4hep-spack main compatibility with spack develop only, and if it isn't it's a legitimate bug to be filed against key4hep-spack.
