### ISSUE TITLE
Build container gcc version lagging behind?

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/key4hep-spack#573]
- OS version: alma9

```
[lreichen@lxplus910 ~]$ g++ --version
g++ (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)
```
while the one used in the nightlies looks to still be 11.3.1 at least from the path, but I am not sure how to figure out which one was used exactly...

I noticed this because ROOT is warning me when generating dictionaries
```
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20221121'
  Extraction of runtime standard library version was: '20230605'
```
(I am also not successful using the generated dictionary but this might also be due to me trying it for the first time)

**Comment by jmcarcell** [comment]
Yep, I just need to update the images.  It may have been like that since November: https://wiki.almalinux.org/release-notes/

**Comment by jmcarcell** [comment]
The new nightlies have been compiled with 11.4.1
