### ISSUE TITLE
Support rocky linux 9 in setup.sh

### ISSUE THREAD

**Issue by giovannimarchiori** [key4hep/key4hep-spack#579]
In our lab our server uses rocky linux 9 and we currently hack the setup.sh of key4hep so that the distribution is recognised as a alma9 and we can then setup, compile and run the software stack successfully.
Would it be possible to do this little modification to the central setup.sh, as long as rocky linux 9 and alma 9 remain binary compatible? 

It's basically a one line addition from

`if [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="centos"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = 'VERSION_ID="7"' ]] ||
   [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="rhel"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = VERSION_ID=\"7* ]]; then
    os="centos7"
    k4path=$(echo /cvmfs/sw-nightlies.hsf.org/key4hep/releases/$rel/*centos7*)
elif [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="almalinux"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = VERSION_ID=\"9* ]
] ||
         [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="rhel"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = VERSION_ID=\"9* ]]; then
    os="almalinux9"
`

to

`if [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="centos"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = 'VERSION_ID="7"' ]] ||
   [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="rhel"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = VERSION_ID=\"7* ]]; then
    os="centos7"
    k4path=$(echo /cvmfs/sw-nightlies.hsf.org/key4hep/releases/$rel/*centos7*)
elif [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="almalinux"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = VERSION_ID=\"9* ]
] ||
         [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="rhel"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = VERSION_ID=\"9* ]]
 ||
         [[ "$(grep -E '^ID=' /etc/os-release)" = 'ID="rocky"' && "$(grep -E 'VERSION_ID' /etc/os-release)" = VERSION_ID=\"9*  ]]; then
    os="almalinux9"
`

Thanks,
   Giovanni

**Comment by tmadlener** [comment]
I don’t see a problem with that. Since you have the changes already I think you could directly open a pull request for this.

**Comment by giovannimarchiori** [comment]
hi @tmadlener ,

done - please see https://github.com/key4hep/key4hep-spack/pull/580

Cheers,
  Giovanni
