### ISSUE TITLE
New Key4hep release for the 2024 FCC week

### ISSUE THREAD

**Issue by BrieucF** [key4hep/key4hep-spack#587]
New features that will be used to produce results for the FCC week (10 - 14 June 2024) have been introduced since the last release (2024-04-12). We would therefore like to ask for a new release including the following:

- [x] Merge https://github.com/key4hep/k4geo/pull/335
- [ ] Tag https://github.com/AIDASoft/DD4hep 
- [ ] Tag https://github.com/key4hep/k4geo
- [ ] Tag https://github.com/HEP-FCC/k4RecCalorimeter
- [ ] Tag https://github.com/key4hep/k4RecTracker

Please comment, add items to this list, etc.

Thanks in advance!

**Comment by tmadlener** [comment]
If we tag FCCAnalyses, we will also have to tag EDM4hep, I think. That would create a very weird intermediate state version of EDM4hep where we can't read anything prior and will also not be able to read anything afterwards (without any additional effort).

**Comment by jmcarcell** [comment]
Closing this since it doesn't seem it's going to happen.
