### ISSUE TITLE
KKMCee Wrapper problem with configfile option -c

### ISSUE THREAD

**Issue by dirkzerwas** [key4hep/key4hep-spack#589]
The KKMCee wrapper does not seem to treat the option "-c,--config FILENAME" consistently:
- KKMCee has the -c, --config FILENAME option
- KKMCee calls the executable as: time ${KKMCEE_EXE} ${_SSEED} -o ${_OUTFILE} -n ${_NEVTS}, so the input file name is not used, I guess this means that KKMCee.exe always expects pro.input as input file.
- KKMCee -c MYCONFIGfile leads to "KKee2f::InitParams: No final state fermions were selected",  expected since KKMCee.exe does not know that MYCONFIGfile contains the configuration
- as a check we added after the lines (around L257) and before the "fi":
EndX
EOF
the two lines:
else
ln -sf $_CONFFILE ./pro.input

afaict the "if" is the check of the absence of $_CONFFILE, so adding the "else" treats the existence of the $_CONFFILE and creates a link to it with the filename expected by KKMCee.exe.

This change makes the job run. Could you have a look? (Maybe it's something else?)

**Comment by jmcarcell** [comment]
The fix is not yet in the nightlies because that change in the wrapper doesn't modify the hash in spack and it considers the version installed is the same as the one it would install so it doesn't do anything.

**Comment by dirkzerwas** [comment]
Hi @jmcarcell,
unless I am mistaken the nightlies seem to be running the version from May 9. I guess this is still stuck due to the SPACK issue?

**Comment by jmcarcell** [comment]
Hi @dirkzerwas, so the issue here was that the changes in #598 are not enough to trigger rebuilds by spack. I made a silly change of a space in a patch in https://github.com/key4hep/key4hep-spack/pull/607. Spack uses the patches to build a hash so it should now be different from the one installed and it should be rebuilt in the nightlies. Let's see tomorrow.

**Comment by dirkzerwas** [comment]
Hi @jmcarcell,
I had a look, your trick installed a new KKMCee in the nightly:
/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-07-04/x86_64-almalinux9-gcc11.4.1-opt/kkmcee/5.00.02-bytybr
but it does not work.
What is bizarre:
grep if  /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-07-04/x86_64-almalinux9-gcc11.4.1-opt/kkmcee/5.00.02-bytybr/bin/KKMCee
gives (among other lines):
if test "x$_CONFFILE" = "x" || test ! -f $_CONFFILE; then
my impression was that in the new wrapper you had separated the two checks?
grep ln ....
gives only:
ln -sf ${KKMCEE_ETC}/KKMCee_defaults
I expected to see also the line you had added:
ln -sf $_CONFFILE ./pro.input

It's as if SPACK built KKMCee, but with the old wrapper or am I mistaken?

**Comment by jmcarcell** [comment]
Indeed it seems the wrapper was not the one I thought it was but was coming from one of the patch files, this should be fixed in #598, let's see tomorrow although this time I built it locally and it looks fine.

**Comment by jmcarcell** [comment]
`-c` now fails when the input file can't be found and I can see in the output of `KKMCee` that the input file is used since its contents are dumped.

**Comment by dirkzerwas** [comment]
just to confirm that it works: I ran muon pair production in k4GeneratorsConfig, thanks!
