### ISSUE TITLE
Pop!_OS 22.04 compatibility

### ISSUE THREAD

**Issue by Juanki0396** [key4hep/key4hep-spack#615]
I am using Pop!_OS 22.04 as my linux  distro in my laptop and my project as a Summer Student needs to source the key4hep stack from cvmfs. Since Pop!_OS is based on Ubuntu it should be compatible with the stack. In fact, I have made a local copy of the '/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh' file and modify it so Pop!_OS 22.04 is recognized as Ubuntu 22.04. Everything seems to work, now I can compile and run my project in my laptop.

**Comment by andresailer** [comment]
Hi @Juanki0396 

Please open a PR with your modifications.
