### ISSUE TITLE
CED transparency bug is back

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/key4hep-spack#625]
previous issue: https://github.com/key4hep/key4hep-spack/issues/516

Broken on Alma9 since `2024-08-03`

Contrary to the last time the FPS have not decreased though. (They even increased, for me previously the graphics were v-synced to 60 Hz)

![image](https://github.com/user-attachments/assets/7bfa8a29-b4d1-41a5-9068-52d29ad276c9)

**Comment by jmcarcell** [comment]
For some reason mesa is now being built in the stack even though it's in the system, before that nightly it seems nothing was asking for it. Should be fixed by also explicitly adding mesa to the packages that are picked up from the system.

**Comment by jmcarcell** [comment]
Can you check this again? I think I see some artifacts but I'm not on Alma 9 so I'm not sure if this works or not.

**Comment by jmcarcell** [comment]
It's fixed now, confirmed by @GiuliaGianoli
