### ISSUE TITLE
Release 2024-09-20ish

### ISSUE THREAD

**Issue by andresailer** [key4hep/key4hep-spack#647]
List of packages (@BrieucF to add)

edit (Thomas): copied all elements to the top level comment to have github pick them up as tasks

edit (Brieuc): add a PR that would be nice to have in k4geo, if possible in time, if not let's proceed 

- [x] DD4hep 1.30  (PR to upstream spack opened: https://github.com/spack/spack/pull/46429)
- [ ] k4geo (would be nice to have https://github.com/key4hep/k4geo/pull/379 in before, done)
- [ ] FCCConfig
- [x] CLDConfig
- [ ] k4RecCalorimeter
- [ ] k4RecTracker
- [x] FCCAnalyses
- [x] k4MarlinWrapper (https://github.com/key4hep/key4hep-spack/pull/654)
- [x] k4EDM4hep2LcioConv (see https://github.com/key4hep/key4hep-spack/pull/638)
- [x] podio (https://github.com/spack/spack/pull/46502)
- [x] EDM4hep (same PR as podio)
- [ ] k4FWCore: https://github.com/key4hep/k4FWCore/pull/243
- [ ] k4reco with https://github.com/key4hep/k4Reco/pull/2
- [x] `k4GeneratorsConfig`
- [x] `ddfastshowerml` (#658)
- [x] `marlinmlflavortagging` (#658)
- [x] LCIO (https://github.com/spack/spack/pull/46556)
- [x] iLCSoft packages #653 
- [x] k4SimDelphes (#661)

**Comment by BrieucF** [comment]
Proposal of packages to be tagged and included for the upcoming release:
- [ ] k4geo
- [ ] FCCConfig
- [ ] CLDConfig
- [ ] k4RecCalorimeter
- [ ] k4RecTracker

Anything else?

**Comment by tmadlener** [comment]
I think we should also start making tags for key4hep-spack again (as we did for some time in the past), to make it easy to reproduce these builds if necessary (spack commits and cherry-picks are then also available from that tag, not just from cvmfs).

**Comment by tmadlener** [comment]
We also need a first tag for the following, I think:
- `k4GeneratorsConfig`
- `ddfastshowerml`
- `marlinmlflavortagging`

**Comment by kjvbrt** [comment]
Hi, following releases are ready:
* k4SimGeant4: [v0.1.0pre15](https://github.com/HEP-FCC/k4SimGeant4/releases/tag/v0.1.0pre15)
* k4Gen: [v0.1pre12](https://github.com/HEP-FCC/k4Gen/releases/tag/v0.1pre12)
* k4RecCalorimeter: [v0.1.0pre14](https://github.com/HEP-FCC/k4RecCalorimeter/releases/tag/v0.1.0pre14)
* FCCConfig: [v0.1.0](https://github.com/HEP-FCC/FCC-config/releases/tag/v0.1.0)
* FCCSW: [v1.0pre10](https://github.com/HEP-FCC/FCCSW/releases/tag/v1.0pre10)
* dual-readout: [v0.1.4](https://github.com/HEP-FCC/dual-readout/releases/tag/v0.1.4)

ATM I'm trying to finish FCCAnalyses in this PR: https://github.com/HEP-FCC/FCCAnalyses/pull/309

**Comment by jmcarcell** [comment]
Since no one complained when changing the compiler to GCC 14 for the AlmaLinux 9 nightly builds I won't make a build with GCC 11 and in some time I will stop building the nightlies with GCC 11 (now it's possible to choose either GCC 14 or GCC 11 with Alma 9).

**Comment by andresailer** [comment]
Makes sense to drop gcc11 soon.

**Comment by kjvbrt** [comment]
Hi, for the FCCAnalyses the new tag is [v0.10.0](https://github.com/HEP-FCC/FCCAnalyses/releases/tag/v0.10.0)

**Comment by jmcarcell** [comment]
> We also need a first tag for the following, I think:
> 
>     * `k4GeneratorsConfig`
> 
>     * `ddfastshowerml`
> 
>     * `marlinmlflavortagging`

These ones are still missing, I can only do `k4GeneratorsConfig`.

**Comment by kjvbrt** [comment]
Hi all and @jmcarcell, there is another release of k4RecCalorimeter with fixes from @tmadlener: [v0.1.0pre15](https://github.com/HEP-FCC/k4RecCalorimeter/releases/tag/v0.1.0pre15)

**Comment by jmcarcell** [comment]
Release 2024-10-03 (when building started) has been deployed (Alma 9) or is in the process (Ubuntu 22). I'll send an email later today after a few things are checked.
