### ISSUE TITLE
`tabulate` missing from EL9 nigtlies

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#649]
`tabulate` seems to be missing from the EL9 nightlies or at least the environment that is generated. Things are working on the Ubuntu 22 nightlies (for the same date).

```console
$ source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
[...]
        source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh -r 2024-09-21
[...]
$ python -c 'import tabulate'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tabulate'
```

This might resolve itself, I mainly opened this because ther is a failing CI job for podio https://github.com/AIDASoft/podio/actions/runs/10990753029/job/30511656589

**Comment by jmcarcell** [comment]
It looks like something went wrong in the installation but it didn't fail: 
```
ls -lah site-packages
total 1.5K
drwxr-sr-x. 3 cvmfs cvmfs  37 Sep 20 18:56 .
drwxr-sr-x. 3 cvmfs cvmfs  27 Sep 20 18:56 ..
drwxr-sr-x. 2 cvmfs cvmfs 142 Sep 20 18:56 UNKNOWN-0.0.0.dist-info
```
The most pragmatic option is to just copy what's installed for Alma9 with GCC 11 and this is already done and deployed on cvmfs. Next time I'll make sure to have a look at this. I think it should be fine now, at least I don't get that error anymore.
