### ISSUE TITLE
Geant4 patches in key4hep will be included in upcoming version 11.3

### ISSUE THREAD

**Issue by atolosadelgado** [key4hep/key4hep-spack#677]
Hi,

Geant4 will make the annual version release in few days. 

This is just a reminder that the patches in key4hep that are currently applied to Geant4 source code, for the twisted tube and the generic trapezoid geometrical shapes, are valid for version 11.2. This patches will be included in the upcoming version 11.3, so I guess you can drop them for the new version. I do not know how to manage this in the key4hep recipe. 

Best,
Alvaro

**Comment by tmadlener** [comment]
I think this already taken care of in the geant4 package in upstream spack:

https://github.com/spack/spack/blob/9bd7483e73f12e341274e7a20cd44b87effeb1fb/var/spack/repos/builtin/packages/geant4/package.py#L232-L233

(assuming that the patch that is applied there is the one that you refere to, it will only be applied for a very specific range of geant4 versions).

**Comment by atolosadelgado** [comment]
Hi @tmadlener 

Thank you for quick reply! It is fine if the patch is applied for a limited number of versions of Geant4. There was another patch for generic trapezoid; if it is not in that recipe, does it mean that it is not applied? :)

**Comment by tmadlener** [comment]
It's possible that it is applied via a patch to the package itself. There @jmcarcell would have to chime in, as I don't know whether we have something like that in our [`.cherry-picks](https://github.com/key4hep/key4hep-spack/blob/main/.cherry-pick)

**Comment by andresailer** [comment]
> It's possible that it is applied via a patch to the package itself. There @jmcarcell would have to chime in, as I don't know whether we have something like that in our [`.cherry-picks`](https://github.com/key4hep/key4hep-spack/blob/main/.cherry-pick)

https://github.com/key4hep/key4hep-spack/blob/b6cb5689f194031638e1a7fb3b4363146a60f5d8/.cherry-pick#L26-L27

**Comment by jmcarcell** [comment]
When I update I have a look at the cherry picks and I remove them if they can be removed, in this case the geant4 ones will be there until the next version and then I'll remove them. Even if I don't remove them it wouldn't matter since they are only applied for versions between 11.2.0 and 11.2.2.
This is the commit that Andre is showing:
https://github.com/spack/spack/commit/c8191268c3ea4aca6e870ad40d695e92f94d0e47
