### ISSUE TITLE
Problem: pick the system GSL (1.15) when building marlinutil 

### ISSUE THREAD

**Issue by mirguest** [key4hep/key4hep-spack#77]
I have tried to install key4hep-stack from scratch on my computer (scientific linux 7.5, gcc 8.3.0), without the external libraries from /cvmfs/sw.hsf.org. The problem is that even though the spack already installs the GSL 2.5, but when building marlinutil, it chooses the system GSL.
```
1 error found in build log:
     64    -- Check for CED_CED_LIBRARY: /home/lintao/k4spack-without-hsf/spack/opt/spack/linux-scientific7-broadwell/gcc-8.3.0/ced-1.9.3-cehr3rif2rrxmwdueeladstn4mp2xmec/lib/libCED.so -- ok
     65    -- Found CED: /home/lintao/k4spack-without-hsf/spack/opt/spack/linux-scientific7-broadwell/gcc-8.3.0/ced-1.9.3-cehr3rif2rrxmwdueeladstn4mp2xmec (Required is at least version "1.4")
     66    -- Check for GSL (1.15)
     67    -- Check for GSL_LIBRARIES: gsl;gslcblas
     68    -- Check for GSL_GSL_LIBRARY: /usr/lib64/libgsl.so -- ok
     69    -- Check for GSL_GSLCBLAS_LIBRARY: /usr/lib64/libgslcblas.so -- ok
  >> 70    CMake Error at /home/lintao/k4spack-without-hsf/spack/opt/spack/linux-scientific7-broadwell/gcc-8.3.0/cmake-3.18.2-vfaqkt6bcebp5f7u74dnpwt7mkmqdbnw/share/cmake-3.18/Modules/FindPackageHandleStandardArg
           s.cmake:165 (message):
     71      Could NOT find GSL (missing: PACKAGE_VERSION_COMPATIBLE) (Required is at
     72      least version "2.1")
     73    Call Stack (most recent call first):
     74      /home/lintao/k4spack-without-hsf/spack/opt/spack/linux-scientific7-broadwell/gcc-8.3.0/cmake-3.18.2-vfaqkt6bcebp5f7u74dnpwt7mkmqdbnw/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (
           _FPHSA_FAILURE_MESSAGE)
     75      /home/lintao/k4spack-without-hsf/spack/opt/spack/linux-scientific7-broadwell/gcc-8.3.0/ilcutil-1.6-x2hyzkx34usdcc2znxudohfxelpk7t4e/cmakemodules/FindGSL.cmake:84 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
     76      CMakeLists.txt:28 (FIND_PACKAGE)


See build log for details:
  /tmp/lintao/spack-stage/spack-stage-marlinutil-1.15.1-zun2vhuaj7ae2yejxzpavid7aengpzon/spack-build-out.txt
```

It looks like the `FindGSL.cmake` from `ilcutil` is used.

**Comment by mirguest** [comment]
My current solution is removing the `NO_DEFAULT_PATH` in the https://github.com/iLCSoft/iLCUtil/blob/master/cmakemodules/FindGSL.cmake#L19. Change from
```
FIND_PROGRAM( GSL_CONFIG_EXECUTABLE gsl-config PATHS ${GSL_DIR}/bin NO_DEFAULT_PATH )
```
to
```
FIND_PROGRAM( GSL_CONFIG_EXECUTABLE gsl-config PATHS ${GSL_DIR}/bin )
```
As descriped in https://cmake.org/cmake/help/latest/command/find_program.html:
> If NO_DEFAULT_PATH is specified, then no additional paths are added to the search.

**Comment by vvolkl** [comment]
Hi @mirguest,

thanks for this report, I think I never had gsl installed as a system package, so I never ran into this issue! I'll add your solution as a patch to the recipe. Maybe you can also open a PR to marlinutil with these changes? (pinging @andresailer  -- Could this be included upstream?)

**Comment by mirguest** [comment]
Hi @vvolkl ,
I am happy to contribute it. 😄 
Tao

**Comment by vvolkl** [comment]
@mirguest is this still relevant? if yes, I think we can try pinging the upstream maintainers again on your PR / adding this as a patch.

**Comment by mirguest** [comment]
Hi @vvolkl ,
I think I could close this issue. I don't see this problem in the latest login nodes. Thanks.
Tao
