### ISSUE TITLE
fccsw requirement for delphes 3.4.3pre05 breaks build

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#82]
delphes in the main spack packages does not have 3.4.3pre05 and  prefers 3.4.2, this breaks the fccsw requirement for 3.4.3pre05

**Comment by vvolkl** [comment]
The `3.4.3pre05` version was merged into the main spack package already before you opened this issue. Maybe you need to update your spack repository? I think this underscores the need to version spack and k4-spack:  https://github.com/key4hep/k4-spack/issues/49

**Comment by vvolkl** [comment]
https://github.com/spack/spack/pull/19304
