### ISSUE TITLE
"Illegal instruction" error using stack build

### ISSUE THREAD

**Issue by carlgwilliam** [key4hep/key4hep-spack#87]
Hi,

I am trying to setup the fcc environment on my centos 7 machine [1] (non lxplus) using the spack build by calling 

source /cvmfs/fcc.cern.ch/sw/latest/setup.sh

as detailed in the startup kit at

https://hep-fcc.github.io/fcc-tutorials/fast-sim-and-analysis/FccFastSimAnalysis.html

When I do that, I get no strange output from the setup script but then basically all commands give "Illegal instructions" e.g.

`[gwilliam@phi build]$ fccrun
Illegal instruction (core dumped)
[gwilliam@phi build]$ diff
Illegal instruction (core dumped)`

I talked about this with Clement Helsens and he suggested I try an LCG build rather than a spack build by calling instead 

https://github.com/HEP-FCC/FCCSW/blob/master/init_lcg_97a_FCC_2.sh

This works fine.

Cheers,

Carl

My system is 

`[gwilliam@phi build]$ echo $SHELL
/bin/bash
[gwilliam@phi build]$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
[gwilliam@phi build]$ uname -a
Linux phi.ph.liv.ac.uk 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux\

**Comment by vvolkl** [comment]
Hi @carlgwilliam,

thanks for reporting this issue! In the key4hep software working group, we came to an agreement to build for the microarchitecture `broadwell` as defined by [archspec](https://archspec.readthedocs.io/en/latest/microarchitectures.html). Although I can't be certain, my guess is that your CPU doesn't support some parts of this instruction set (at least, this would give the exact same error ).  Building for more general instruction sets comes with a performance trade-off, but I can bring this up again at the next meeting. As clement said, for now, you should be able to use the LCG releases.

**Comment by mirguest** [comment]
Hi @carlgwilliam ,

I agree with @vvolkl, the CPU maybe different . I had the illegal instruction problem before: a package called fftw3 is built on an Intel-based CPU, which will be automatically optimized with the Intel specific feature. When it is invoked in an AMD based CPU, the program crashed.

You can check your CPU with `lscpu` command. For example, here is the CPU info at IHEP server:
```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                28
On-line CPU(s) list:   0-27
Thread(s) per core:    1
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
Stepping:              1
CPU MHz:               1200.000
CPU max MHz:           2000.0000
CPU min MHz:           1200.0000
BogoMIPS:              3995.14
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-6,14-20
NUMA node1 CPU(s):     7-13,21-27
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts

```

Tao

**Comment by carlgwilliam** [comment]
Hi,

Thanks both for the info.  The CPU is an intel one as follows so not sure it if can be that.

`
[gwilliam@phi build]$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
Stepping:              4
CPU MHz:               1200.390
CPU max MHz:           3600.0000
CPU min MHz:           1200.0000
BogoMIPS:              5599.84
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d
`

Cheers,

Carl

**Comment by carlgwilliam** [comment]
Sorry, that got Mal formatted (and for some reason I can't edit it). It is

[gwilliam@phi build]$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
Stepping:              4
CPU MHz:               1200.390
CPU max MHz:           3600.0000
CPU min MHz:           1200.0000
BogoMIPS:              5599.84
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d

**Comment by mirguest** [comment]
Thanks @carlgwilliam ,
The micro-architecture of your CPU `Intel(R) Xeon(R) CPU E5-2680 v2` is `Ivy Bridge` [1]. Ivy Bridge is two generation older than Broadwell [2]. 

[1] https://ark.intel.com/content/www/us/en/ark/products/75277/intel-xeon-processor-e5-2680-v2-25m-cache-2-80-ghz.html?q=E5-268
[2] https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures
