### ISSUE TITLE
llvm 11.0.0 seems to cause python conflicts

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#95]
See spack/spack#19666

Changing packages.yaml to build 10.0.1 seems to work

**Comment by vvolkl** [comment]
Looking at the upstream discussion, this seems to be a tricky issue, and it's probably best to use your workaround.

**Comment by joequant** [comment]
This turns out not to be a huge problem for key4hep-stack for now, since a better solution is to build mesa without LLVM.  No need to address this here, and closing issue.
