### ISSUE TITLE
Add regression tests to build

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#97]
This is item for general discussion, but now that I've got automated builds running, I'd like to start doing automated regression testing, and I'm interested in the best way of specifying tests to be run.   This may be an upstream spack issue

**Comment by vvolkl** [comment]
That's in principle very easy: `spack --tests=all install key4hep-stack`. However, see #89 ...

**Comment by jmcarcell** [comment]
This [adding regression tests to the build itself] is probably not happening any time soon, testing can be done as Valentin mentioned, and it's done that way for the nightlies. Closing stale issue.
